### ISSUE TITLE
inconsistency in dpp flag for norm(,2) and quad_form()

### ISSUE THREAD

**Issue by tm4droid** [cvxgrp/cvxpy#1038]
**Describe the bug**
norm(W @ V) is dpp while quad_form(W, V@ V) is not dpp where W is PSD

**Version**
 - OS: Windows 10 64bits
 - CVXPY Version: 1.1.0.0a4

**Additional context**
in context of portfolio optimization. total variance and total volatility of a portfolio are calculated with these two formulas when W is the asset weights vector. and V is square root of covariance matrix.

**Comment by akshayka** [comment]
DPP prohibits multiplying parameters together (so V*V) is not allowed. This is by design, and is documented here:

https://www.cvxpy.org/tutorial/advanced/index.html#disciplined-parametrized-programming

We recommend representing parametrized quadratic forms via the square root and a sum_squares atom, eg, cp.sum_squares(V@W).

**Comment by tm4droid** [comment]
I used V * V for explanation. The question is why quad_form(W, X) is considered non dpp, and norm(W@V) considered dpp.

**Comment by akshayka** [comment]
The mapping from the coefficient matrix of a quadform to the problem data is not affine (for conic standard form), so the coefficient matrix cannot be parametrized. 

The website documentation mentions this exception, but perhaps it could be more clear?

> In other cases, you can represent non-DPP transformations of parameters by doing them outside of the DSL, e.g., in NumPy. For example, if P is a parameter and x is a variable, cp.quad_form(x, P) is not DPP. You can represent a parametric quadratic form like so:
