### ISSUE TITLE
Better error messages for non-Expression input to CVXPY atoms.

### ISSUE THREAD

**Issue by PKUFlyingPig** [cvxgrp/cvxpy#1079]
I want to add a simple norm constraint to my problem, it seems like below:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/60659728/87557779-ed0e3680-c6ea-11ea-94da-cdd8d43a99a2.png">
But it doesn't work !
<img width="778" alt="image" src="https://user-images.githubusercontent.com/60659728/87557842-00210680-c6eb-11ea-81ce-47f1f9c6a837.png">
Also I am a little confused by the max function, if I want to add a constraint like max(x,1) <= x+y, how should I write to satisfy cvxpy rule?

**Comment by rileyjmurray** [comment]
The issue is a subtle one. When CVXPY parses input to various nonlinear functions ("atoms"), it checks if the input is a CVXPY Expression object. If the input is such an object, then it proceeds by parsing that object symbolically (including all Variable objects). If the input to a CVXPY atom is *not* a CVXPY Expression, then it tries to cast that input to a constant. You are seeing an error because the input ``val = [x,y]`` to ``cp.norm(val)`` is a *list* rather than a CVXPY Expression.

In your situation, you should first concatenate ``x`` and ``y`` to form ``val = cp.bmat([x,y])`` and then use ``cp.norm(val)``. You can find other concatenation and vector-formation functions at: https://www.cvxpy.org/tutorial/functions/index.html#vector-matrix-functions.

For your second question, since ``max`` is a convex function, you can write ``max(expr1) <= expr2`` without trouble. Note that your usage of ``max`` should only take one argument (a concatenation of ``x`` and ``1``).

**Comment by PKUFlyingPig** [comment]
Thanks a lot for your patient answers! Also thanks a lot for such an amazing software you guys developed !!

**Comment by rileyjmurray** [comment]
Steven and Akshay and I are in favor of introducing a more useful error message for people who find themselves in this situation. I'm re-opening this issue until such an error message is introduced.

**Comment by SteveDiamond** [comment]
I added an error for invalid list input to atoms. It raises an error for the different examples you've mentioned.
