### ISSUE TITLE
cvxpy 1.1.3 does not support ECOS_BB solver

### ISSUE THREAD

**Issue by vpozdnyakov** [cvxgrp/cvxpy#1100]
**Describe the bug**
cvxpy 1.1.3 does not support ECOS_BB solver
cvxpy 1.0.31 supports ECOS_BB solver

**To Reproduce**
`$pip uninstall cvxpy`
`$pip install cvxpy`

`import cvxpy as cp`
`assert 'ECOS_BB' in cp.installed_solvers()`

**Expected behavior**
cvxpy 1.1.3 supports ECOS_BB solver

**Version**
 - OS: MacOs Mojave 10.14.6
 - CVXPY Version: 1.1.3

**Comment by SteveDiamond** [comment]
ECOS_BB was intentionally dropped, because it's buggy and unreliable.

**Comment by vpozdnyakov** [comment]
Hello, @SteveDiamond. Unfortunately, others (I tried CBC and GLPK_MI) do not solve my problem. Could you give me an advice? Perhaps I use incorrect formulation.

```python
total = 100
weight = np.array([0.25, 0.25, 0.25, 0.25])
x_weight = cp.Variable(4, nonneg=True)
y_count = cp.Variable(4, integer=True)
obj = cp.Minimize(cp.sum_squares(x_weight - weight))
constr1 = (y_count == total * x_weight)
constr2 = (cp.sum(x_weight) <= 1)
problem = cp.Problem(obj, [constr1, constr2])
problem.solve()
```

```
SolverError: Either candidate conic solvers (['CBC, GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg, Zero), or there are not enough constraints in the problem.
```

**Comment by rileyjmurray** [comment]
SCIP is now CVXPY's open-source mixed-integer nonlinear solver. You may need to install CVXPY from source, as I'm not sure if there has been a CVXPY release with SCIP yet.

**Comment by sjiekak** [comment]
@vpozdnyakov I need the same and wrote a version with ecos (based on 1.1.3 + the ecos_bb of 1.0.31)

https://github.com/sjiekak/cvxpy/releases/tag/v1.1.3_ecosbb

@rileyjmurray 

SCIP license is quite restrictive (only academic and non-commercial users), compared to ecos which is GPL v3

**Comment by rileyjmurray** [comment]
@sjiekak it's true that licenses for commercial usage of ECOS_BB and SCIP differ. However, GPL v3 is an extremely restrictive license. Michael Grant created the ``cvxpy-base`` conda package because commercial users needed to avoid ECOS as an installation dependency of the full version of CVXPY.

We still welcome additional open-source mixed-integer nonlinear solvers. If someone writes a reliable such solver with an Apache license, we'd be happy to include such a solver in the default installation of CVXPY. Until someone contributes such a solver, I think the best thing to do is for people to use your fork.
