### ISSUE TITLE
cp.quad_form().is_convex() returns False when matrix is positive definite

### ISSUE THREAD

**Issue by marchinidavide** [cvxgrp/cvxpy#1217]
I see an unexpected behavior in `cp.quad_form()` where the matrix input is positive definite.
I my understanding when P is positive definite, the atom `quad_form` should always return `True` when calling `.is_convex()`.
What am I missing?

```python
import numpy as np
import cvxpy as cp

np.random.seed(0)
size = 10
w_min = 0.01
cov = np.random.randn(1000, size)
cov = cov.T @ cov / 1000

weights = cp.Variable(size)
weights_pos = cp.pos(weights - w_min)
print(weights.is_convex()) # True, as expected
print(weights_pos.is_convex()) # True, as expected
qform0 = cp.quad_form(weights, cov)
qform1 = cp.quad_form(weights_pos, cov)
qform2 = cp.quad_form(cvx.pos(weights - w_min), cov)
print(qform0.is_convex()) # True, as expected
print(qform1.is_convex()) # False, should be True?
print(qform2.is_convex()) # False, should be True?
```

 - OS: macOS Catalina 10.15.7
 - CVXPY Version: 1.1.7

**Comment by rileyjmurray** [comment]
Whether or not ``.is_convex`` returns ``True`` depends not just on the function itself (here, ``quad_form``) but also on the arguments that have been passed to the function. In your case, the expression ``qform2`` is not a quadratic form in the mathematical sense, because you've used the ``pos`` atom as an argument. I'm reasonably certain that when viewed as a function of ``weights``, the expression ``qform2`` is not convex.

I'm closing this issue for now. If you believe that (1) the mapping is convex, and (2) the composition of functions satisfies [DCP rules](https://www.cvxpy.org/tutorial/dcp/index.html#curvature-rules), then we can re-open this.

**Comment by marchinidavide** [comment]
My bad, it's definitely not convex.
Thank you for the impeccable feedback!
