### ISSUE TITLE
Old NAG (<26.2) interface of cvxpy

### ISSUE THREAD

**Issue by pqrz** [cvxgrp/cvxpy#1254]
Given the cvxpy documentation states that: It accepts `NAG `solver if one is able to: `import naginterfaces`

But old version of NAG (<26.2) - has no support for `naginterfaces`, instead it uses `nag4py`.

So, can cvxpy handle old NAG releases also?

In case not, would it be possible to add that?

**Comment by SteveDiamond** [comment]
Could you say more about why you can't use the latest NAG release?

**Comment by pqrz** [comment]
Sure. 
The reasons is: our systems are using the legacy code for commercial `NAG`,  since the codebase is very large and susceptible to break - we are continuing with the legacy code. 

Also given `naginterfaces` is quite a recent happening, first released in mid-2018 and **covering NAG v26.2 to NAG v27** [0], whereas `nag4py` covers **NAG v23 to NAG v26** [1][2] - We expect there would be more organizations like us.

In terms of cvxpy, we request more of **extension**, rather then **replacement** - as in if cvxpy could extend its support for old NAG interface too (without removing the existing new NAG interface) - then it would be win-win for everyone.

0 - https://www.nag.com/numeric/py/nagdoc_latest/changelog.html#changes-in-version-26-2-0-0
1 - https://anaconda.org/NAG/nag4py/files
2 - https://www.nag.com/content/downloads-nag-python-bindings-nag4py

**Comment by SteveDiamond** [comment]
@shuanghuabai what do you think about this? We could add a new solver interface for the old NAG interface.

**Comment by shuanghuabai** [comment]
Thanks for the query. Could you clarify what problems you want to solve via cvxpy? nag4py is a legacy product. The new NAG Libraries saw some important updates to deliver significantly better performance with the new solvers so we didn't consider to include it in the cvxpy.

However, there might be a way for you - our new naginterfaces include the old legacy nag4py so in theory you can update to naginterfaces without changing your source but use the latest NAG Python bindings which would allow you to access cvxpy. NAG is doing quite a lot to preserve a backward compatibility among our Library releases so I hope you wouldn't hit any major issues with your legacy system. Would you mind contacting us directly via support@nag.com so that we can discuss your problem in detail?

**Comment by pqrz** [comment]
1. We are using NAG to solve SOCP, MISOCP problem majorly and using **NAG v25**
2. It is really helpful to know - _"you can update to naginterfaces without changing your source but use the latest NAG Python bindings"_. So, correct me if wrong - `naginterfaces` do covers NAG v23 to NAG v27, (with the same underlying configuration [0]).

BTW - In that case which distribution of `naginterfaces` from [1] should one download?

0 - https://www.nag.com/doc/inun/cl25/l6idcl/un.html#accessing
1 - https://www.nag.com/downloads/py/naginterfaces_nag/naginterfaces/

**Comment by shuanghuabai** [comment]
Re (2): naginterfaces Mark 27.1 (the new Python binding of the new NAG Library) includes a legacy layer nag4py so instead of calling
  import nag4py...
you will only need to change to
  import naginterfaces.nag4py
and in principle everything should be working. 

To be exact, this naginterfaces.nag4py provides the same interfaces as nag4py but for the latest NAG Library underneath (i.e., it is not that the package would include Mark25, it is built above the Mark 27.1 Library, however, this library should be backwards compatible with older marks in a majority of cases). You will also need to update your license (please contact us over support@nag.com). Therefore I recommend to install the latest (Mark 27.1) and choose the one matching your system, see installation instructions here: https://www.nag.com/numeric/py/nagdoc_latest/readme.html#installation

If everything works, I would suggest that we close this issue. It would be really helpful to know what routines you are using so that we can help you more so please do get in touch with our support.

**Comment by pqrz** [comment]
Thanks for the info!

Just wanted to circle back to the question we started.
Now given that `naginterfaces` is backward compatible, can we conclude that - **One can use NAG (via cvxpy) and still access Mark25 release (atleast theoretically)**.
