### ISSUE TITLE
Group transforms, represented by matrices (SO2, SE3, etc)

### ISSUE THREAD

**Issue by morzh** [cvxgrp/cvxpy#1285]
Sorry for a dummy question, but is there a way to parametrize transformation matrix by some parameters. E.g. rotation matrix on a plane  has single parameter (angle) and of 2x2 size. Toy problem i want to solve is
`argmin_{theta} \sum_k ||R(theta) x_k - y_k||`
`x_k` and `y_k` are given points on a plane

Thanks in advance

P.S. Tried to implement my own Atom, stuck at  `graph_implementation`

[atom_exp_so2.py.txt](https://github.com/cvxgrp/cvxpy/files/6148048/atom_exp_so2.py.txt)

**Comment by rileyjmurray** [comment]
Hi @morzh, welcome to the CVXPY GitHub. You can't create a general-purpose convex atom for optimizing over SO2 or SO3, largely because the set of rotation matrices in either situation is not convex. An analytic solution might be available for your toy problem. You can try looking at the orthogonal Procrustes problem: https://en.wikipedia.org/wiki/Orthogonal_Procrustes_problem. Further discussion of this kind is better suited for either Stack Overflow or our recently created (and currently beta) GitHub Discussions board: https://github.com/cvxgrp/cvxpy/discussions.
