### ISSUE TITLE
For Python2+Python3 compatibility, add some `from __future__` imports.

### ISSUE THREAD

**Issue by argriffing** [cvxgrp/cvxpy#164]
https://github.com/cvxgrp/cvxpy/pull/150#issuecomment-68882598

These are used in numpy and scipy, so if the tests pass locally using Python 2, they will probably also work with Python 3.

**Comment by SteveDiamond** [comment]
Right now cvxpy is using the ``use_2to3=True`` flag in ``setup.py`` so that a Python 2 (or Python 3) compatible version is built automatically. It's been very convenient. You can use ``a//b`` in the code and it will convert it into ``int(a/b)``. It would seem that the ``from __future__`` imports aren't necessary.

What's your opinion on this approach? @rmcgibbo added Python 3 support. I don't have any previous experience with Python 3.

**Comment by argriffing** [comment]
> What's your opinion on this approach?

Thankfully I didn't have to suffer through these transitions for numpy, scipy (https://github.com/scipy/scipy/pull/397), IPython (https://github.com/ipython/ipython/issues/2440), sympy (http://ondrejcertik.blogspot.com/2013/08/how-to-support-both-python-2-and-3.html), etc. so I don't have first-hand battle stories to explain why it is a good idea, but apparently it is the consensus 'best practice' for Python 2 and 3 support, despite the fact that it conflicts with the original advice in http://legacy.python.org/dev/peps/pep-3000/.

**Comment by rmcgibbo** [comment]
In my opinion, the most important thing for multilingual python development
is the CI system -- especially if, as a developer, you're working only with
one of py27/py34, you're pretty likely to accidentally introduce trivial
incompatibilities unless the CI warns you. But given the notifications from
the CI, it's usually trivial to maintain cross-version compatibility.

I've worked with both single codebase py2/py3 projects (usually using the
six library to make things more smooth) and with projects that use 2to3.
For starting new projects, I always go with single codebase, and recommend
it to to others. Development is easier, because thing like `setup.py
develop` work better when source translation isn't required. Also,
debugging py3-specific issues can be a little trickier when the "canonical"
source is not runnable in the py3 interpreter.

But it's not that big of a deal. When the project is already working just
fine with 2to3, changing it to single-codebase style shouldn't be a
priority, IMO.

**Comment by keithbriggs** [comment]
What does "CI" stand for?

**Comment by argriffing** [comment]
> What does "CI" stand for?

It's continuous integration, like [Travis](https://travis-ci.org) or [Jenkins](http://jenkins-ci.org/).
