### ISSUE TITLE
IP Knapsack Specific Data Breaks ECOS

### ISSUE THREAD

**Issue by cmale** [cvxgrp/cvxpy#167]
I setup a simple IP to solve a generic knapsack problem. I have been running this code for a month and it's been fine but with the following values it breaks the ECOS solver:

import cvxpy as cvx
import numpy as np

knapsack_cap = 25
item_vals = np.array([[ 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 4, 0, 0, 4, 0.25, 0.25, 0, 0, 0, 0, 3, 0.5, 3 ]])

# Optimize
total_pickup_val = cvx.Variable()
pickup_flags = cvx.Bool(item_vals.shape[1])
objective = cvx.Maximize(total_pickup_val)
constraints = []

constraints.append(total_pickup_val == item_vals * pickup_flags)
constraints.append(total_pickup_val <= knapsack_cap)
                
# Solve
prob = cvx.Problem(objective, constraints)
prob.solve(verbose=True)

print "status:",prob.status
print "optimal value", prob.value

Here is the output:

ECOS 1.1.0 - (c) A. Domahidi, ETH Zurich & embotech 2012-15. Support: ecos@embotech.com

It     pcost         dcost      gap     pres    dres     k/t     mu      step     IR
 0   -2.510e+01   -5.166e+01   +6e+01   3e-01   1e+00   1e+00   1e+00    N/A     1 1 -
 1   -2.486e+01   -2.816e+01   +8e+00   4e-02   1e-01   3e-01   2e-01   0.8727   0 0 0
 2   -5.334e+00   -6.019e+00   +9e-01   4e-01   2e+00   4e+01   2e-02   0.8946   0 0 0
 3   -2.472e+01   +1.247e+02   +5e-02   7e-02   3e-01   2e+02   1e-03   0.9723   0 0 0
 4   -2.471e+01   +1.421e+04   +6e-04   7e-02   3e-01   1e+04   1e-05   0.9890   1 0 0
 5   -2.470e+01   +1.291e+06   +7e-06   7e-02   3e-01   1e+06   1e-07   0.9890   2 0 0
 6   -2.470e+01   +1.171e+08   +7e-08   7e-02   3e-01   1e+08   2e-09   0.9890   1 0 0
 7   -2.469e+01   +1.061e+10   +8e-10   7e-02   3e-01   1e+10   2e-11   0.9890   2 0 0

PRIMAL INFEASIBLE (within feastol=1.2e-10).
Runtime: 0.000189 seconds.

status: unbounded
optimal value inf

This is very strange, for instance if you change the first value of the item_vals array from 2 to 1, the problem is feasible and an optimal solution is found. If you keep increasing the first value it stays infeasible.

This seems like a bug but if there's an explanation any hep would be appreciated. Thanks.

**Comment by SteveDiamond** [comment]
It worked for me when I increased the maximum number of iterations for ECOS BB:
```
prob.solve(verbose=True, solver=cvx.ECOS_BB, mi_max_iters=2000)
```
Solver options like this are documented here:
http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#solve-method-options

cvxpy can't guarantee a solution for mixed-integer problems (since they're not convex). cvxpy calls ECOS BB, which runs for mi_max_iters (default 1000) steps and then returns the best solution found. In this case no feasible point was found. I think there's a bug where dual and primal infeasibility are being grouped together. I've created an issue for ecos: 

https://github.com/embotech/ecos/issues/114
