### ISSUE TITLE
Reduce build and install dependencies

### ISSUE THREAD

**Issue by mcg1969** [cvxgrp/cvxpy#241]
While `cvxpy` certainly needs _a_ solver in order to function properly, it should not _depend_ on having them just to intsall it. If I were to use `cvxpy` with Gurobi, for example, I shouldn't have to install `ecos`, `scs`, etc. just to install it. Thoughts?

**Comment by SteveDiamond** [comment]
I agree it shouldn't depend on the solvers, but I do want the easiest way to install cvxpy (``pip install cvxpy``) to also install a sufficient set of solvers. That makes it a lot easier for new users, who don't know anything about the different solvers available or how to install them.

I've listed ``ecos``, ``scs``, and ``cvxopt`` as dependencies in ``setup.py`` so that pip installs them. If there's some other way to have pip install the solvers, I'm totally open to it.

**Comment by mcg1969** [comment]
If they don't know anything about the different solvers, then I would suggest that installing three solvers isn't too helpful. Instead I suggest they be guided gently into just one, and I'd recommend ECOS. CVXOPT in particular is a heavy dependency, and its default install is not necessarily the version I'd recommend. So my suggestion is, at a minimum, to drop `scs` and `cvxopt` as dependencies.

**Comment by mcg1969** [comment]
The reason I'm asking is that I'm considering building a Conda package for this. This in turn requires building conda packages for all dependencies, and some are easier than others. What I'm likely to do is live-patch the `setup.py` script to remove those dependencies for conda.

**Comment by mcg1969** [comment]
OK, now that I understand how tightly woven cvxopt is into some of your code, I understand it's not practical to ask that it be removed as a dependency.

**Comment by SteveDiamond** [comment]
The issue with only installing ecos is it can't solve SDPs. Otherwise I would agree with you. cvxopt and scs aren't the greatest SDP solvers, but they're better than nothing.

Yeah, there's a lot of functionality for converting cvxopt matrices into numpy ndarrays and vice versa, which may not be necessary. cvxpy actually works without ecos or scs, and it would be nice if it worked without cvxopt.

Doesn't cvxopt have a conda package though?

**Comment by mcg1969** [comment]
Not in the main channel, no. It's not trivial to build with all of its capabilities, really. But I did just build one in my own channel with GPLK and FFTW. I went ahead and build a CVXPY package with that dependency. I have an ECOS package as well but not SCS, so I patched that out.

**Comment by mcg1969** [comment]
I did study your code well enough to conclude that, with some effort, it could be made to run without CVXOPT. The interface approach you've built is a good one, but there are still a couple of hardcoded places where you depend in a "hard" way on CVXOPT.

**Comment by ajfriend** [comment]
I've never made a conda package, so I'm not sure what goes into it, but
what's the current problem with SCS? I'm writing a Cython interface for SCS
to add some functionality, so I could potentially help with tweaking things
to get it to work with conda.

**Comment by mcg1969** [comment]
I don’t want to have to build packages I don’t need. That’s the problem. :-)
 
 
Michael C. Grant, Ph.D.
Senior Solution Architect
Continuum Analytics, Inc. <http://continuum.io/> 	Convex optimization resources:
CVX <http://cvxr.com/cvx/>, TFOCS <http://cvxr.com/tfocs/>, CVX Forum <http://ask.cvxr.com/> 
CVX Research, Inc. <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://continuum.io/> 	 <http://cvxr.com/>

**Comment by mcg1969** [comment]
Just to be clear, if I were just installing CVXPY on a single computer, it would be no big deal. What I’m exploring is building conda packages (basically binary distributions) for CVXOPT, CVXPY, etc. And to do that I need to handle all of their dependencies as well.
 
 
Michael C. Grant, Ph.D.
Senior Solution Architect
Continuum Analytics, Inc. <http://continuum.io/> 	Convex optimization resources:
CVX <http://cvxr.com/cvx/>, TFOCS <http://cvxr.com/tfocs/>, CVX Forum <http://ask.cvxr.com/> 
CVX Research, Inc. <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://continuum.io/> 	 <http://cvxr.com/>

**Comment by ajfriend** [comment]
No problem! I just saw a potential overlap since I'd like to streamline the
SCS python install: You need to run `pip install numpy` and 'pip insteall
scs' since the SCS installer depends on numpy. I'd like to get it down to
just the one command, if possible.

While I'm doing that, if its not too much work, I might make a conda
package for SCS anyway, since I'm sure that would be useful to people.

**Comment by mcg1969** [comment]
I do think that it would be beneficial if y’all would build and maintain conda packages for everything. Anaconda is without a doubt the easiest Python distribution for people to use, especially for numerical applications. I’m not saying that just because I work here---I am working here in part because I was impressed with Anaconda & their other projects!

Here’s everything I built the other day.

	https://anaconda.org/mcg
 
 
Michael C. Grant, Ph.D.
Senior Solution Architect
Continuum Analytics, Inc. <http://continuum.io/> 	Convex optimization resources:
CVX <http://cvxr.com/cvx/>, TFOCS <http://cvxr.com/tfocs/>, CVX Forum <http://ask.cvxr.com/> 
CVX Research, Inc. <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://continuum.io/> 	 <http://cvxr.com/>

**Comment by echu** [comment]
I wonder if we could go with this approach:

CVXPY vanilla only depends on CVXOPT
If users attempt to use a *different* solver, throw a help message that says something like, "Install with pip / conda ..."

OR

Provide a script ("cvxpy install") to install additional solvers. This might be messy since not everybody uses the same Python build system. I personally use virtualenv + pip, but I know conda is extremely popular. I've also been bitten on projects where I'm using pip, but others are using conda. So... this route could be really tricky.

Along with the script, you'd provide an API call, something like, `cvxpy.install("scs")`.

I actually think @mcg1969's concern / suggestion is a good one. In fact, one extreme is for CVXPY to ship with *no* solvers. (IIRC, this is probably very difficult.) The plugin approach would let others write solver plugins for CVXPY etc. and lead to a cleaner and more maintainable project in the long run. Furthermore, when a particular solver doesn't work, that owner can deal with the issue. ;-)

**Comment by mcg1969** [comment]
I know that it may seem convenient to have solvers as a dependency, but it really isn't that difficult to install one if they are made available via pip and/or conda.

What I would propose is that you remove *all* solver dependencies, including CVXOPT. CVXOPT is actually a pretty big and cumbersome package, and it also uses some outdated matrix code. It would serve people well to standardize on NumPy/SciPy at this point. But to accomplish this, you'd need to replace a couple of CVXOPT assumptions with Scipy.

Then, in the manual, I'd add something like this:

> cvxpy requires a convex optimization engine to solve the models you create. It does not ship with one of its own, because the proper choice depends on the specific types of problems you are solving. If you aren't sure, we recommend ECOS (link). Installing ECOS is easy: if you're using the Anaconda distribution or some other conda-based distribution, just type
> 	conda install ecos
> If you're using pip, type
> 	pip install ecos
> Of course, there are several other solvers you might consider; for more information, consult the "Solvers" section of the manual.

Finally, I would add an error message that is issued when someone tries to solve a model without a solver installed that effectively provides the same information. Perhaps it could detect if Conda is installed and offer that command instead of the Pip equivalent.

 
Michael C. Grant, Ph.D.
Senior Solution Architect
Continuum Analytics, Inc. <http://continuum.io/> 	Convex optimization resources:
CVX <http://cvxr.com/cvx/>, TFOCS <http://cvxr.com/tfocs/>, CVX Forum <http://ask.cvxr.com/> 
CVX Research, Inc. <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://cvxr.com/> <http://continuum.io/> 	 <http://cvxr.com/>

**Comment by SteveDiamond** [comment]
This all sounds reasonable. I'll remove the hard cvxopt dependency in the cvxpy 1.0 release, at a minimum. This will mean dropping support for cvxopt matrices, but that's probably for the best like you say.

**Comment by SteveDiamond** [comment]
Actually, CVXOPT matrices are already unusable as constants because they don't support operator overloading properly. So there's no reason whatsoever to keep the CVXOPT dependency.

**Comment by twiecki** [comment]
This would be great and make deployment of this library much easier.

**Comment by jerluc** [comment]
@SteveDiamond @mcg1969 Perhaps an easy way to provide optional dependency inclusion is to use [setuptools extras declarations](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies). I personally haven't used them before in my own projects, but I've definitely installed plenty of libraries in the past that use this feature.

A great example of this is [Dask](http://dask.pydata.org/en/latest/install.html#pip), which allows you to install the library using one of:

``` bash
pip install dask[complete] # Install everything
pip install dask[array] # Install dask and numpy
pip install dask[bag] # Install dask and cloudpickle
pip install dask[dataframe] # Install dask, numpy, and pandas
pip install dask # Install only dask, which depends only on the standard library
```

You can see how their [setup.py looks like with the extras declared](https://github.com/dask/dask/blob/master/setup.py), it certainly looks pretty straight-forward.

**Comment by RhysU** [comment]
A separate motivation for dropping the hard cvxopt dependency is its GPL licensing precludes doing anything else with cvxpy.  I've heard rumblings of a re-license for 1.0.

**Comment by SteveDiamond** [comment]
The hard CVXOPT dependency is already gone. This issue is still open because of the hard ECOS and SCS dependencies.

**Comment by GiorgioBalestrieri** [comment]
Although I understand the idea of making life easier for new users, I don't think it should come at a cost for _all_ users. 

One solution is to include them as optional dependencies ([documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), so that `pip install cvxpy` only gets cvxpy and the "real" dependencies installed, whereas `pip install cvxpy[solvers]` installs scs, ecos and so on. You could even have specific `[ecos]` and `[scs]` options to select a specific package.

**Comment by SmokinCaterpillar** [comment]
Yes, can you please remove ecos from the install requirements? It is a GPL licensed library and this makes commercial applications of cvxpy problematic.

**Comment by phschiele** [comment]
@tmh-alex you should be able to install `cvxpy-base`, which is deployed alongside `cvxpy` and does not contain the solvers:

https://www.cvxpy.org/install/index.html?highlight=cvxpy+base#install-without-default-solvers
