### ISSUE TITLE
Broken dependence on multiporcess?

### ISSUE THREAD

**Issue by aringh** [cvxgrp/cvxpy#258]
I have just installed Anaconda3-2.4.1 on my Ubuntu 14.04 computer, and was trying to install `cvxpy`. However, there seems to be a broken dependence on the `multiprocess` package. I get the following error when installing:
```
Collecting multiprocess (from cvxpy)
  Using cached multiprocess-0.70.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p4mkpfvu/multiprocess/setup.py", line 66, in <module>
        meta_fh = open(os.path.join(here, '%s/__init__.py' % libdir))
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-p4mkpfvu/multiprocess/py3.5/multiprocess/__init__.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p4mkpfvu/multiprocess
```
I don't know if this is a pure `cvxpy` error, or if it is also of interest for @mmckerns ?

**Comment by mmckerns** [comment]
I think the issue might be that the `multiprocess-0.70.3` release predates stable `python3.5` support.  Explicit (rather than implicit) support for `python3.5` was added Oct 5, 2015, a few months after the release you are using.  Essentially, I need to cut a new `multiprocess` release -- I must have overlooked that I needed a release after the explicit add of support for `python3.5`.  I'm guessing if you install the version of `multiprocess` on github, your issue will go away.

**Comment by aringh** [comment]
Works perfect. Thanks!

( For a potential reader that might be less familiar with how to install from a repository: it means that you have to run `pip install git+https://github.com/uqfoundation/multiprocess.git`. See for example http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch )

**Comment by SteveDiamond** [comment]
I'm glad there's a fix! @mmckerns could you update the multiprocess version on pypi so that people don't get this error when installing with pip?

**Comment by mmckerns** [comment]
@SteveDiamond: Yes, I'll do that.  I *thought* I had already cut a release that supported `3.5` explicitly, but apparently I was mistaken. A new release should be up this week.
