### ISSUE TITLE
matrix definition

### ISSUE THREAD

**Issue by akhani** [cvxgrp/cvxpy#290]
Two questions:
1- Can a QP with asymmetric P be solved with CVXPY? Currently I get an error on P not being symmetric!
2- When I use PP=P+P.T, I get the error "P has both positive and negative eigenvalues". I know that P doesn't have negative eigenvalues (P is lower triangular with nonnegative diagonal elements). How do I go about solving this problem.
Thank you for your help.

**Comment by discardthree** [comment]
Hi,

Your first question is purely one of interface.  I don't know if CVXPY gives an error for asymmetric P, but there's no loss of generality if it does because you can make your problem symmetric without changing it's meaning by letting ``P = 0.5*(P+P.T)``.

For your second question, although I think the eigenvalues of a lower triangular matrix lie on its diagonal entries, I have a counterexample that shows that the eigenvalues can be negative after symmetrizing as above.

Ex:
```python
[[ 1, 0]
 [-4, 1]]
```
is lower triangular with nonnegative diagonal entries, but the symmetrized matrix
```python
[[ 1, -2]
 [-2, 1]]
```
is definitely not positive semidefinite since its determinant ``1*1 - (-2)*(-2) = -3`` is negative.  Not being PSD means it must have at least one negative eigenvalue.

I may be missing something, but it would seem that you need to check for nonnegativity of the eigenvalues post-symmetrization to find out of your problem is actually a convex problem.  As in the counterexample, the signs of the eigenvalues before symmetrization can lead you to think your problem is convex when it isn't.

**Comment by akhani** [comment]
It seems that I overlooked the effect that symmetrization might have on the matrix definition. Thank you for your quick and detailed answer.

**Comment by SteveDiamond** [comment]
Also, in the current version of cvxpy, ``quad_form(x,P)`` doesn't require that ``P`` be symmetric. You should upgrade your cvxpy if you can.
