### ISSUE TITLE
CVXPY speed issue since CVXOPT dependency dropped

### ISSUE THREAD

**Issue by cmale** [cvxgrp/cvxpy#312]
I am using CVXPY with GLPK_MI solver. This requires CVXOPT to be installed. I noticed since upgrading to the latest version of CVXPY, runtime has increased 5x. I was previously using CVXPY v 0.3.7, but have tested with versions up to 0.4.2 and did not see a significant change in solver speed until updating to 0.4.3 when the CVXOPT dependency was dropped. 

I noticed that there have been issues in the past #130 #154 that seem to be related.  

I am working to provide an example that I can share shortly but in the meantime if there's any suggestions on this issue please let me know.

**Comment by SteveDiamond** [comment]
Probably the change in runtime is due to the 0.4.3 refactor. After the refactor the CVXOPT and GLPK(_MI) solver interfaces generate SciPy sparse matrices and convert them to CVXOPT sparse matrices. Previously they just generated CVXOPT sparse matrices. It's not related to #130 and #154. 

The change was necessary in order to remove the CVXOPT dependency, so I can't really offer any remedy. If GLPK_MI is really the solver you need I would stick with the older CVXPY versions. CVXPY 1.0 will handle solver interfaces in a totally different way, and I'll keep your issue in mind.

**Comment by cmale** [comment]
Thanks for the quick reply. I need a (cheap) MILP solver and GLPK_MI has been my best bet so far, I'll try the new support for Cbc and compare performance.
