### ISSUE TITLE
problem.solve() changes problem data

### ISSUE THREAD

**Issue by roversch** [cvxgrp/cvxpy#353]
On branch `1.0`, in `test_linear_cone.py`, `test_vector_lp` fails. This is due to line 129:

    result_new = p_new[0].solve()

which somehow overwrites the data of p_new. More specifically, the right hand side becomes [1, 1] instead of the original [1, 2]. If I comment out this line and the following assert, the test works.

I've tracked the problem down to `matrix_data.py:181`: 

    V, I, J, const_vec = canonInterface.get_problem_matrix(
                active_constr,
                self.sym_data.var_offsets,
                constr_offsets
            )

Note that the `const_vec` returned is correct, but the data in `active_constr` gets changed somehow inside CVXcanon.

**Comment by akshayka** [comment]
Here's a silly, temporary workaround: replace 

    V, I, J, const_vec = canonInterface.get_problem_matrix(
                active_constr,
                self.sym_data.var_offsets,
                constr_offsets
            )

with

    V, I, J, const_vec = canonInterface.get_problem_matrix(
                copy.deepcopy(active_constr),
                self.sym_data.var_offsets,
                constr_offsets
            )

**Comment by roversch** [comment]
Could it be that the `constr_offsets` are wrong?

**Comment by SteveDiamond** [comment]
Deep copying is not something that we can do in the release version. It's way too inefficient. CVXcanon is supposed to work without copying data.

**Comment by akshayka** [comment]
Oh yes, of course. But it appears that CVXCanon modifies the constraint data in place.

**Comment by akshayka** [comment]
Sorry, prematurely hit enter. It is unclear to me whether get_problem_matrix is supposed to modify the constraints in place -- the semantics of the function are not clear because it is not sufficiently documented. I will need to spend time reading the code before I can properly debug it.

**Comment by akshayka** [comment]
Line 124 of `canonInterface.py` is the offending line:

    linC.set_dense_data(format_matrix(linPy.data))

In particular, before executing this line, `linPy.data == array([[1.], [2.]])`. After executing this line, `linPy.data == array([[1.], [2.]])`. The offending function is `set_dense_data`: after executing format_matrix, `linPy.data` still equals `array([[1.], [2.]])`; however, the value of `linPy.data` is changed to `array([[1.], [1.]])` after `set_dense_data` is executed.

**Comment by akshayka** [comment]
It seems canonInterface might have been a red herring.

On line 85 of cone_matrix_stuffing.py, we obtain the offset vector `b` for each constraint by calling the `get_coeffs` method of `QuadCoeffExtractor`. This method returns a flattened version of the offset vector: in our case, the effect is that `b := np.array([1, 2])` instead of `b := np.array([[1], [2]])`. In the subsequent line of `cone_matrix_stuffing.py`, within the constructor of `reshape`, `b` is cast to a `Constant`; however, because the shape of `b` is (2,), the `is_1D_array` field is set to `True` in the Constant constructor, even though the `_value` field is set to a 2D-array and the `_shape` field is set to `(2,1)`. My hunch is that this discrepancy triggers the pathological behavior somewhere down the road. But this hunch could certainly be wrong.

Replacing `R.flatten()` in lines 79 and 181 of `utilities.quadratic.py` with `R` solves the problem: with this change, `test_linear_cone` passes and the data in the problem constraints are no longer modified by `CVXCanon`. That said, I do not know whether other code paths depend upon `R` being flattened. Are there any tests for `utilities.quadratic.py`?

All of this seems a bit weird and perhaps symptomatic of a/another lurking bug, somewhere.

**Comment by SteveDiamond** [comment]
There's ``test_ls.py``, which uses ``utilities.quadratic.py``. Nothing tests it directly that I'm aware of. It looks like the code is designed to always return a 1D array, so I'm not sure it's a good idea to remove the flattening. We also will need to change the ``Constant`` constructor to handle 1D arrays (now it makes everything 2D). The ``is_1D_array`` field is a hack to handle some weird edge cases where 1D and 2D arrays behave differently.

I agree that this doesn't quite seem like the root of the bug. I would leave ``utilities.quadratic.py`` as it is for now and come back to this bug later, after we add support for 1D arrays.
