### ISSUE TITLE
Installation docuementation

### ISSUE THREAD

**Issue by bmeyers** [cvxgrp/cvxpy#354]
The [install guide](http://www.cvxpy.org/en/latest/install/index.html) doesn't make any mention of installing with `pip`. As of 4/18/17, `pip install cvxpy` works as expected, installing the latest version of the software and installing all dependencies. `nosetests cvxpy` is successful.

Running Python 2.7.12 on Mac OS 10.12.4 inside a `virtualenv` (version 10.0.3).

**Comment by SteveDiamond** [comment]
That's right. The installation instructions used to be based on ``pip``, but you would not believe how many people managed to do it incorrectly. It was a never ending source of problems for me. That's why Anaconda is the only *supported* installation method. Of course people can install cvxpy however they like. They just can't expect help with unsupported methods. I'll add something about ``pip`` though with the discussion of installation from source.

**Comment by bmeyers** [comment]
Makes perfect sense to me. Some context: @stephenpboyd had asked me to make an issue for this, so I complied. 

Cheers,
Bennet

**Comment by SteveDiamond** [comment]
pip installation is now mentioned in the docs.
