### ISSUE TITLE
how to set soft constraint to get a relaxed solution?

### ISSUE THREAD

**Issue by leolle** [cvxgrp/cvxpy#384]
I read the document, it says it supports soft constraint with different priority on each constraint. 

But I can't find any examples, can anybody help?

For example, I have a portfolio optimization problem, I want to set constraints on my asset weight and factor exposure with priority of 2 and 1 respectively, they are all inequality functions.

**Comment by sschnug** [comment]
What document did you read? How do you expect help with such sparse information? (searching for soft within cvxpy's docs results in nothing; seems you are not talking about the official documentation).

**Comment by leolle** [comment]
@sschnug I read the cvx_portfolio document.

**Comment by sschnug** [comment]
First: i really don't get why you write something like ```I read the document, it says it supports soft constraint with different priority on each constraint.``` when you are speaking about a paper (and an accompanying library) not directly connected to cvxpy. Then, when asked, instead of a link you just mention ```the cvx_portfolio document``` which keeps us guessing (why not just link it?).

I'm assuming you are speaking about the paper [Multi-Period Trading via Convex Optimization
](https://web.stanford.edu/~boyd/papers/pdf/cvx_portfolio.pdf) and the code [here](https://github.com/cvxgrp/cvxportfolio).

Reading the part about soft-constraints:

- it is exactly explained what you have to do to achieve this within that paper
- it is not mentioned, that there is an automatic function available to do this (search for ```soft``` in repository returns {})

So please read the part again carefully and try to implement the sketch. If it's not working, present your own approach in a detailed way instead of asking broad/general questions like "how to do that?".

And maybe more important:

- **this is an issue-tracker -> it's about bugs and not about discussing modelling-questions**
  - there is a user-group for this
- **cvxportfolio is an own project (which also seems work in progress)** -> not really the best idea to ask within cvxpy's community (yes, it's used internally; but you are probably to use the application-specific functions in this project)

**Comment by leolle** [comment]
@sschnug thank you for your reminder.
