### ISSUE TITLE
Prefer MOSEK bas solution over itr

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#405]
https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/mosek_intf.py#L246 prefers the MOSEK itr solution over the bas when both are equally good.  Please make the converse possible as a configurable CVXPY behavior via http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#solve-method-options.

**Comment by RhysU** [comment]
Doubleplusgood if it might land in 0.4.x.

**Comment by rileyjmurray** [comment]
@RhysU 

This is a feature in 1.0. All you need to do is call "problem.solve(solver='MOSEK', bfs=True)". As long as your problem was a linear program (or representable as one, i.e. for 1-norm minimization), then you will get the expected result.

I don't think this feature will be added to cvxpy 0.4. The master branch is supposed to switch to 1.0 in the very near future.

@SteveDiamond , can you confirm that this feature will not be added for 0.4? If so, then this issue can be closed.

**Comment by SteveDiamond** [comment]
That's correct, there will be no more changes to 0.4 (unless someone finds a truly horrible bug).
