### ISSUE TITLE
Positive semidefinite quad_form => Problem does not follow DCP rules (cvxpy 1.0)

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#407]
I have noticed that cvxpy 1.0 complains about the convexity of QPs with semidefinite Hessian. Here is the MWE:

```python
import cvxpy
import scipy.sparse as sparse

# Define problem data
P = sparse.csc_matrix([[4., -4., 0.],
                       [-4., 8., -4.],
                       [0., -4., 4.]])
#  P += 1e-10 * sparse.eye(3)  # Uncomment to make it work


# Define CVXPY problem
x = cvxpy.Variable(P.shape[0])

# Standard objective
objective = cvxpy.quad_form(x, P)

problem = cvxpy.Problem(cvxpy.Minimize(objective), [x <= 1., x >= 0])
problem.solve()
```

This code returns the error
```python
DCPError: Problem does not follow DCP rules.
```
I suspect this is related to the eigenvalues of `P` which are (12, 4, 0) but the last one appears to be `-1.34708082e-16` if computed via
```python
lam, _ = np.linalg.eig(P.todense())
```

By uncommenting one line in the first code snippet everything works. Would it make sense to add a tolerance on the negativity of the eigenvalues of `P`?

**Comment by rileyjmurray** [comment]
In practice, if you face this issue you should reformulate the problem.

Suppose P is PSD with eigendecomposition P = U * D * U'. Then in your case, you would solve the problem:

min y' * D * y :  0 <= x <= 1, y = U' * x

By reformulating things this way it should be clear to the user that sufficiently small negative values in D should be set to zero.

**Comment by rileyjmurray** [comment]
Follow-up: this has some overlap with #442 . In that situation a projection operation for PSD matrices is performed in standard arithmetic, but the result of that projection is tested against hard equality constraints (rather than np.allclose( ... )). As a result, even positive _definite_ parameter matrices can fail tests for being PSD.

The issue in #442 really does seem to be a matter of correctness, rather than convention. Assuming it gets fixed, there's a chance that cvxpy would allow you to declare your matrix P as a PSD cvxpy Parameter (since the projection of P onto the PSD cone could have sufficiently small residual). Such behavior is undesirable because it creates inconsistency with (1) recognizing P as a PSD Parameter, but (2) refusing to allow P.value to appear in a quadratic form.

**Comment by rileyjmurray** [comment]
Here is a possible solution (one that I've recommended in a few other issues):

If you have a PSD matrix that *might* be singular, then you must define it as a cvxpy Parameter with keyword argument PSD=True. This will change the check for PSD-ness from "check nonnegativity of approximate eigenvalues", to "check residual after approximate projection onto the PSD cone".

The following code works properly:
```
import cvxpy
import numpy as np

# Define problem data
P = np.array([[4., -4., 0.],
                       [-4., 8., -4.],
                       [0., -4., 4.]])

# Define CVXPY problem
x = cvxpy.Variable(P.shape[0])

# Standard objective
objective = cvxpy.quad_form(x, cvxpy.Parameter(shape=P.shape, value=P, PSD=True))

problem = cvxpy.Problem(cvxpy.Minimize(objective), [x <= 1., x >= 0])
problem.solve()
```

@SteveDiamond, @bstellato is that an appropriate solution to this problem? (I.e., can we add the above recommendation to cvxpy documentation and close this issue?)
