### ISSUE TITLE
Elemental-interface ignores solver-state

### ISSUE THREAD

**Issue by sschnug** [cvxgrp/cvxpy#414]
During some test-like CQP-solving, it occured to me, that the Elemental-wrapper
always returns with ```optimal```, no matter what happens during solving.

A simple example would be:

    import numpy as np
    import cvxpy as cvx

    x = cvx.Variable(1)
    constraints = [x >= 1, x <= 0]                  # infeasible
    objective = cvx.Minimize(cvx.sum_entries(x))
    problem = cvx.Problem(objective, constraints)

    print('ECOS')
    problem.solve(solver=cvx.ECOS)
    print(problem.status)

    print('ELEMENTAL')
    problem.solve(solver=cvx.ELEMENTAL)
    print(problem.status)

which outputs:

    ECOS
    infeasible
    ELEMENTAL
    Uncaught exception
    Uncaught exception
    Process 0 caught error message:
    Reached maximum number of iterations, 1000, with rel. error 5.18727e+13 which does not meet the minimum tolerance of 0.000102648

    optimal

It looks to me the original author [was aware](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/elemental_intf.py#L205) of that:

    results_dict = {'info': {'exitFlag': 0, 'pcost': local_c.dot(local_x)},
                'x': local_x, 'y': local_y, 'z': local_z}

Elemental is also printing out a problem-description, everytime there is something wrong.
But of course this does not follow cvxpy's flag-based approach closely.

Now i'm not sure:

- how important this is for people
- how suited Elemental's code including the python-wrapper is to change it
    - (did not find status/flags on first search; looks heavily exception-driven to me)

I think there should be some kind of warning (at least in the docs or the wrapper-code) that
it's deviating a bit here.

---

**Unrelated to cvxpy** (Elemental-only question targeting author)

I'm just pinging @poulson here and take this opportunity to ask him about some unrelated other stuff:

While trying to implement a robust CQP-IPM, i did some prototype-like testing of it against alternatives on the Maros/Meszaros set and looked too at other solvers including yours which looks nice and massive (in terms of different methods and features; even ignoring the core-feature of Elemental.

Can you give some idea about how you estimate the robustness of your Direct/Affine Mehrotra-style
QP-solvers? Did you check them against the above dataset or more using the tasks you / your users
are trying to solve?

I'm asking because some preliminary results (not scientific, not very significat yet) indicate that it's having some trouble, even compared to my own possibly broken method (augmented; LU; path-following) and the more general ECOS (remark: i tested the QP-solvers directly and the SOCP-solver using cvxpy), often complaining about the very first system to solve (minimum tolerance not reached). It might also be possible that a classic Mehrotra-style initial-point works more robust (again; everything preliminary).

What source is this solver based on? cvxopt is mentioned, but you also seem to use quasi-definite solvers (and regularization). I think, as indicated somewhere, your references-file is not complete there (and code-comments only talk about init vs. cvxopt i think).

I'm just trying to learn and do understand that the above findings are just broad and scratching the
surface. Also some instances from this set are probably very *ugly*.

Thanks!

**Comment by poulson** [comment]
Hi sschnug,

Yes, the solvers in HEAD are not very robust. I was almost done with a rewrite in the `lp_data` branch that was trying to achieve HOPDM performance over the netlib LP suite in addition to similarly fast convergence for Delsarte bounds (which often require thousands of bits of precision and break most heuristics): https://github.com/elemental/Elemental/tree/lp_data/src/optimization/solvers

I never finished and merged this rewrite, for various reasons. The main one being that Elemental was originally an MPI-only project, and so many of its algorithmic and architectural choices are regrettable given that very few people use any of the MPI features. For example, the dparse direct solvers I built use nested dissection since this is scalable to distributed architectures, while Approximate Minimum Degree orderings are not (though they are much better for most on-node KKT systems). 

So the interior point method work ended up a victim of the larger project starting to buckle under its own weight.

I would recommend just disabling the Elemental wrappers.
