### ISSUE TITLE
Question about the element in Variable(Matrix)

### ISSUE THREAD

**Issue by 10132510143cai** [cvxgrp/cvxpy#433]
Is it possible to add one element in Variable(Matrix) into the constraints?
For example,
A = Variable(10, 8)
I want to define constraints like that
constraints = [A[3][3]>=1]
(A[3][3] means the element at the third row and the third col of A)

Thank you

**Comment by sschnug** [comment]
The correct indexing is (like in numpy/scipy):

    A[3,3]
    A[3][3]  # wrong!

By design, this sub-access is something which feels like a matrix of size (1,1) then:

    A[3,3]
    Expression(AFFINE, UNKNOWN, (1, 1))

Also keep in mind, that indexing is 0-based. This will index the 4th row and 4th column!

(This is an issue-tracker. It's for bugs and such! For usage-questions, consider using the [mailing-list](https://groups.google.com/forum/#!forum/cvxpy))
