### ISSUE TITLE
What are all the required dependencies when doing pip install?

### ISSUE THREAD

**Issue by chengrunyang** [cvxgrp/cvxpy#437]
Is there a list for all the dependencies that I need to manually install in pip (besides doing `pip install cvxpy`)? I did pip install on a linux server (on which doing conda install is not a viable option), but the convex optimization problem I am trying to solve gets stuck at `prob.solve()`. My code, however, can be normally executed on a Mac where I installed cvxpy using conda. I suspect this is due to the lack of several required packages, but have no idea which ones are missing. 

The error information shown in terminal every time I interrupted the code:

```
  File "runtime_approximation.py", line 125, in model_selection_single_dataset
    result = prob.solve()
  File "/home/cy438/py3.5/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/home/cy438/py3.5/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/home/cy438/py3.5/lib/python3.5/site-packages/cvxpy/problems/solvers/scs_intf.py", line 108, in solve
    return self.format_results(results_dict, data, cached_data)
  File "/home/cy438/py3.5/lib/python3.5/site-packages/cvxpy/problems/solvers/scs_intf.py", line 130, in format_results
    status = self.STATUS_MAP[results_dict["info"]["status"]]
KeyError: 'Interrupted'
```

Any hints? Thanks!

**Comment by sschnug** [comment]
According to the [docs](http://www.cvxpy.org/en/latest/install/index.html#install-from-source) (assuming you are not trying out the 1.0 branch) you should be good to go after a-priori install of numpy  and scipy. 

So *my guess* is, that your problem is to be found somewhere else!

Interpreting the (short) output of yours, it seems all those internal processings are working out and the error occurs during solving, so it seems CVXCanon might be ok (no proof though).

As your error is basically a *can't interpret SCS's return-status* and the status itself (*interrupted*), i guess your SCS install is broken! (I think the dependency of ECOS/SCS is somewhat the reason for the recommendation of the anaconda-based architecture)

What i propose:

- Call the tests
    - I'm not 100% familiar with those and i think missing commercial solvers will result in a lot of garbage
    - Try something like: ```nosetests cvxpy.tests.test_scs``` (or ```nosetests -s --verbosity=3 cvxpy.tests.test_scs``` to increase verbosity)
        - You will need to install ```nosetests``` of course
- Try your code with ```prob.solve(solver=cvx.ECOS)``` (adapt to your import-style) and see if it runs with ECOS instead of SCS

Of course this won't make your code run, but might help in further debugging!

(Out of curiosity: why is anaconda not a viable option in your case?)

**Comment by SteveDiamond** [comment]
I added the "Interrupted" error code to the SCS interface. Other than that this is outside the scope of what we can deal with sadly. If you use OpenMP with SCS I'm not surprised it breaks nosetests, which itself is some sort of parallel/OpenMP run.
