### ISSUE TITLE
Mosek interface in 1.0

### ISSUE THREAD

**Issue by aszekMosek** [cvxgrp/cvxpy#440]
First of all huge thanks to @rileyjmurray for the tremendous work. Two things I wanted to discuss:

1. For an integer problem the dual solution does not exist. In fact (and the only reason you don't see it with current Mosek 8.1 is because of a bug on our side) accessing the dual values raises an exception:

```
mosek.Error: (2950) No dual information is available for the integer solution.
```

2. This is more of an open question in the spirit of #434. In version 0.4 we had a selector between interior point and basic solution depending on quality. The issue #405 even asks to make it configurable. Let me know what you think.

**Comment by rileyjmurray** [comment]
I'll be working on these things in the coming days / weeks. 

I'll also be looking into mapping cvxpy standard options (e.g. max_iters) to corresponding mosek parameter names. Right now if a user wants to change a mosek setting they have to do so by providing a dictionary from parameter names (as strings) to values. This difference in parameter specification can make it difficult for end-uses to use cvxpy in a solver-agnostic way.

**Comment by rileyjmurray** [comment]
When the user asks for mosek to solve an LP, mosek_qpif.py is called, instead of mosek_conif.py.

If we want the user to be able to select the basic solution from the simplex optimizer, then either (1) this change needs to happen in mosek_qpif.py, or (2) mosek_qpif.py needs to be removed, so that mosek_conif.py is called for all problem classes.

cvxpy is capable of reformulating QP's as conic programs, and the backend of the mosek API actually does this conversion as well. If mosek's QP solver *didn't* perform this conversion, and could somehow exploit sparsity in the quadratic-form problem data, then it would make sense to keep the QP interface. However as it stands, mosek_qpif.py is redundant, and increases the complexity of maintaining cvxpy (particularly in writing test code, and handling solver parameters).

What are your thoughts @aszekMosek and @SteveDiamond ?

**Comment by SteveDiamond** [comment]
Removing mosek_qpif.py seems best.

**Comment by bstellato** [comment]
The only reason I see to keep the QP interface is that the SOCP conversion in Mosek, i.e., the matrix factorization, might happen more quickly (probably in plain C (?)) than in CVXPY (in numpy/scipy). Otherwise it is just more work to maintain it.

**Comment by rileyjmurray** [comment]
@bstellato I agree that the factorization might happen faster, since it's written in plain C. However as long as the user has a decent python distribution, numpy's matrix factorization should be performed in C. Also, by doing the conversion within cvxpy, the result of a user's call to prob.get_problem_data('MOSEK') will more closely match the problem that mosek's solver operates on (in the current form, the result of a call to get_problem_data won't show that an SOCP conversion was performed).

**Comment by bstellato** [comment]
Haven't thought of `prob.get_problem_data`. It totally makes sense to remove `mosek_qpif.py`. As you mentioned before, it also makes it easier to maintain it.

**Comment by rileyjmurray** [comment]
Great. Will do then!

**Comment by rileyjmurray** [comment]
Updates:
* mosek_qpif.py has been removed.
* mosek_conif.py has been added to the set of modules tested in test_qp.py.
* all nosetests passing (except for designated cases in test_constant_atoms.py, and test_grad.py, which are likely due to bugs in my alpha-release of mosek 9).
* dual variables are removed for integer programs.
* basic-feasible solution selection allowed for LP's (test added to test_mosek_conif.py; see below)

`            x = cvx.Variable(shape=(2,))
            objective = cvx.Minimize(-4 * x[0] - 5 * x[1])
            constraints = [2 * x[0] + x[1] <= 3,
                           x[0] + 2 * x[1] <= 3,
                           x[0] >= 0, x[1] >= 0]
            prob = cvx.Problem(objective, constraints)

            # Default solution (interior point)
            prob.solve(solver=cvx.MOSEK)
            self.assertAlmostEqual(prob.value, -9)
            self.assertItemsAlmostEqual(x.value, [1, 1], places=5)

            # Basic feasible solution
            prob.solve(solver=cvx.MOSEK, bfs=True)
            self.assertEqual(prob.value, -9)
            self.assertItemsEqual(x.value, [1, 1])
`

Anything else I should work on?

**Comment by rileyjmurray** [comment]
@SteveDiamond this issue can be marked as resolved.
