### ISSUE TITLE
Infinity norm for matrices different than convention

### ISSUE THREAD

**Issue by sbarratt** [cvxgrp/cvxpy#443]
According to the documentation, the function `norm(X, 'inf')` when X is a matrix computes \sum_{i,j}|X_{i,j}|, which is different than the convention, \max_i \sum_j |a_{i,j}|. This could lead to some confusion.

source: http://mathworld.wolfram.com/MatrixNorm.html

**Comment by rileyjmurray** [comment]
Hmm. Yes there is a discrepancy here.

In cvxpy 0.4, I think it makes sense to keep the current implementation. A large number of users may have run into this same discrepancy and simply changed their code accordingly.

The situation is a little different with cvxpy 1.0. Version 1.0 is designed to be as numpy compatible as possible, and numpy uses the same convention that you've pointed out. The result is that in version 1.0, the cvxpy Expression objects

expr1 = cvxpy.norm(X, 'inf')
and
expr2 = np.linalg.norm(X, np.inf) 

have different dimensions, even though the user's intent is indistinguishable.

@SteveDiamond , since version 1.0 is yet to be fully released, do you think it would be reasonable to have cvxpy's norm function behave in the same way as numpy's norm function? In addition to the matrix infinity-norm, there's also the matrix 1-norm.

**Comment by SteveDiamond** [comment]
Yes, this behavior should be changed for cvxpy 1.0. Thanks for pointing this out!

**Comment by rileyjmurray** [comment]
I've made the changes necessary to resolve this issue. It will be included in my next pull request.

**Comment by rileyjmurray** [comment]
This can be marked as resolved.
