### ISSUE TITLE
one unit test about mosek fails in 1.0 branch

### ISSUE THREAD

**Issue by mickeydonkey** [cvxgrp/cvxpy#449]
My mosek version is 8.1.41, installed by conda. This seems a compatibility issue, and I am wondering which version of mosek should I try.
here is the log infomation:

```
======================================================================
ERROR: test_mosek_LP_solution_selection (cvxpy.tests.test_mosek_conif.TestMosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tao.luo/Projects/cvxpy/cvxpy/tests/test_mosek_conif.py", line 192, in test_mosek_LP_solution_selection
    prob.solve(solver=cvx.MOSEK, bfs=True)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/problems/problem.py", line 361, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/problems/problem.py", line 453, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/reductions/chain.py", line 66, in invert
    solution = r.invert(solution, inv)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 475, in invert
    dual_vars = MOSEK.recover_dual_variables(task, sol, inverse_data)
  File "/home/tao.luo/Projects/cvxpy/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 536, in recover_dual_variables
    task.getsnxslice(sol, inverse_data['n0'], inverse_data['n0'] + snx_len, snx)
  File "/home/tao.luo/miniconda2/envs/cvxpfl/lib/python2.7/site-packages/mosek/__init__.py", line 5146, in getsnxslice
    raise Error(rescode(res),msg)
Error: (2953) snx is not available the basis solution.
```

**Comment by rileyjmurray** [comment]
Interesting. Mosek 8 should be fully supported. However, the unit tests I ran were with an alpha release of Mosek 9. I can say that "snx" refers to dual variables for second order or exponential cone constraints. Since the given problem was an LP (and the solution type requested was a basic feasible solution) it makes sense for Mosek to return an error when attempting to access "snx" (even a length-zero slice of it). 

The problem can be fixed by executing lines 535-537 in mosek_conif.py *if and only if* snx_len > 0.

**Comment by mickeydonkey** [comment]
@rileyjmurray  I believe unit tests against Mosek 8 must be passed before the PR #448  is merged. Mosek 8 is easily available via conda.  There is another failed test after I follow your fix above, and I am pretty sure it is due to precision issue.
`
======================================================================
FAIL: test_mosek_LP_solution_selection (cvxpy.tests.test_mosek_conif.TestMosek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tao.luo/Projects/cvxpy/cvxpy/tests/test_mosek_conif.py", line 194, in test_mosek_LP_solution_selection
    self.assertItemsEqual(x.value, [1, 1])
AssertionError: Element counts were not equal:
First has 1, Second has 0:  0.9999999999999999
First has 1, Second has 0:  1.0000000000000002
First has 0, Second has 2:  1

----------------------------------------------------------------------

`

**Comment by rileyjmurray** [comment]
PR 448 is already merged. There are no API differences in the implementation between mosek 8 and 9 (at least none that are used in cvxpy), so no dedicated tests were run on mosek 8. However from the first issue you mentioned, there are some underlying differences between mosek 8 and 9 that affect the unittests (e.g. how get_snx behaves when requesting a slice of length 0) and those differences should be corrected. 

It seems that in addition to the original get_snx issue, there is the matter of precision even when selecting basic feasible solutions (although the unittest you mention did pass on my machine, under the assertItemsEqual implementation). In order to simultaneously support mosek 8 and 9, I agree that the the test should be changed to assertAlmostEqual. However since it's specifically testing recovery of basic feasible solutions, that unitttest should be run at very high precision (say, 10 decimal places, versus the default of 5 or 6).

Can you try to re-run tests using assertAlmostEqual and see what happens? From the error messages it looks like there may also be an issue with dimension mismatches (which I don't have a good explanation for).

**Comment by mickeydonkey** [comment]
PR #451 works fine on my machine, and I can set higher precision digits for base solution later, could you please take a look? BTW, it's not dimension mismatch, just precision issue.

**Comment by mickeydonkey** [comment]
PR #451 works fine on my machine, and I can set higher precision digits for base solution later, could you please take a look? BTW, it's not dimension mismatch, just precision issue.

**Comment by mickeydonkey** [comment]
PR #451 works fine on my machine, and I can set higher precision digits for base solution later, could you please take a look? BTW, it's not dimension mismatch, just precision issue.

**Comment by mickeydonkey** [comment]
PR #451 works fine on my machine, and I can set higher precision digits for base solution later, could you please take a look? BTW, it's not dimension mismatch, just precision issue.

**Comment by mickeydonkey** [comment]
PR #451 works fine on my machine, and I can set higher precision digits for base solution later, could you please take a look? BTW, it's not dimension mismatch, just precision issue.

**Comment by SteveDiamond** [comment]
Hi I merged in the PR and was going to close this, but now I'm wondering if it was premature. It all looked good to me but @rileyjmurray should take a look too in this case.

**Comment by rileyjmurray** [comment]
The only thing I can think of is that checks for "y_len > 0" and "suc_len > 0" should probably be added in recover_dual_variables, right after current lines 522 and 528. 

Although things are passing tests at present, it's probably better to be safe-than-sorry and make the changes now.

**Comment by rileyjmurray** [comment]
@SteveDiamond 

This issue can be marked as resolved.
