### ISSUE TITLE
canonicalizing complex quadratic forms

### ISSUE THREAD

**Issue by AlanKuurstra** [cvxgrp/cvxpy#466]
I'm trying to perform least squares on complex data with quadratic constraints.  The simple example is as follows:

```python
from cvxpy import *
import numpy as np

m = 10
n = 5
np.random.seed(1)
A = np.random.randn(m, n) + 1j*np.random.randn(m, n)
b = np.random.randn(m) + 1j*np.random.randn(m)

tmp = np.random.randn(m, n)+1j*np.random.randn(m, n)
Q1 = np.dot(tmp.transpose(1,0).conj(),tmp)

tmp = np.random.randn(m, n)
Q2 = np.dot(tmp.transpose(1,0),tmp)

# Construct the problem.
x = Variable(n,complex=True)
objective = Minimize(sum_squares(A*x - b))
constraints = [quad_form(x,Q1) <= 3,
               quad_form(x,Q2) <= 3]

prob = Problem(objective, constraints)

print "Optimal value", prob.solve()
print "Optimal var"
print x.value # A numpy matrix.
```

I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/home/akuurstr/cvxpyComplexTest.py", line 29, in <module>
    objective = Minimize(sum_squares(A*x - b))
  File "/softdev/akuurstr/python/thirdparty/cvxpy_top/build/lib.linux-x86_64-2.7/cvxpy/atoms/sum_squares.py", line 36, in sum_squares
    return quad_over_lin(expr, 1)
  File "/softdev/akuurstr/python/thirdparty/cvxpy_top/build/lib.linux-x86_64-2.7/cvxpy/atoms/quad_over_lin.py", line 34, in __init__
    super(quad_over_lin, self).__init__(x, y)
  File "/softdev/akuurstr/python/thirdparty/cvxpy_top/build/lib.linux-x86_64-2.7/cvxpy/atoms/atom.py", line 44, in __init__
    self.validate_arguments()
  File "/softdev/akuurstr/python/thirdparty/cvxpy_top/build/lib.linux-x86_64-2.7/cvxpy/atoms/quad_over_lin.py", line 108, in validate_arguments
    super(quad_over_lin, self).validate_arguments()
  File "/softdev/akuurstr/python/thirdparty/cvxpy_top/build/lib.linux-x86_64-2.7/cvxpy/atoms/atom.py", line 64, in validate_arguments
    "Arguments to %s cannot be complex." % self.__class__.__name__
ValueError: Arguments to quad_over_lin cannot be complex.
```

Is it possible to perform complex least squares?  Should I use something other than sum_squares?

**Comment by AlanKuurstra** [comment]
For now I'm just modifying the objective function:
objective = cvxpy.Minimize(cvxpy.sum_squares(cvxpy.real(A*x - b)) + cvxpy.sum_squares(cvxpy.imag(A*x - b)))

**Comment by rileyjmurray** [comment]
Right now, `cvxpy.sum_squares` is implemented by a call to `cvxpy.quad_over_lin` where the linear argument is 1. `quad_over_lin` doesn't accept complex arguments, so it throws an error. It would be pretty simple to modify `quad_over_lin` so that it handled complex arguments correctly (i.e. by taking an absolute value first), but I'm not sure if that will happen anytime soon.

In your situation, I would just minimize cvxpy.norm( A*x - b, p=2). It's eminently reasonable to assume that the norm function haves correctly for complex variables, so if this is not the case then it should be fixed.

**Comment by AlanKuurstra** [comment]
Thanks for the reply.

Using cvxpy.norm works when there's no constraints.  When I add a quadratic constraint it results in 

```
ValueError: Cannot reduce problem to cone program
```

**Comment by rileyjmurray** [comment]
Well, took quite a bit of digging to figure out what was happening here...

The issue can be traced back to `quad_canon()` in `cvxpy/reductions/complex2real/atom_canonicalizers/matrix_canon.py`. 

On lines 89 and 90 a variable called `matrix` is defined. That variable is an appropriate real block matrix of the real and imaginary parts of the original matrix parameter (`Q1` in your case). The local variable `matrix` is a CVXPY Expression object.

The intended behavior of `quad_canon` is to return another quad_form Expression, this time with the CVXPY Expression `vec` as the variable, and the CVXPY Expression `matrix` as the, well, matrix. The problem is that if `temp = expr.copy([vec, matrix])`, then `temp.is_convex() == False` in spite of `matrix` being positive definite.

The simplest fix is to import the CVXPY Constant module (from cvxpy.expressions.constants) and reassign `matrix = Constant(matrix.value)` right before the call to `expr.copy(...)`. By doing this CVXPY is able to keep track of the fact that `matrix` (whether a CVXPY Expression, or a CVXPY Constant) is positive definite. 

That said, it's weird that we have to do this. If CVXPY needs to determine curvature of a parameterized function, it shouldn't make a difference for if the parameter is a CVXPY Expression with .is_constant() == True, or a CVXPY Constant.

**Comment by rileyjmurray** [comment]
@AlanKuurstra 

For now, the following should work

```
lifted_Q1 = np.bmat([[np.real(Q1), -np.imag(Q1)],
                     [np.imag(Q1), np.real(Q1)]])
lifted_x = cvxpy.hstack([cvxpy.real(x), cvxpy.imag(x)])
# ^ Seems like it should be vstack, 
# but the dimensions only work out correctly with hstack.

constraints = [cvxpy.quad_form(lifted_x, lifted_Q1) <= 3]
```

I've verified that it works on my machine when you do this.

**Comment by SteveDiamond** [comment]
Ok, so to clarify the issue is it doesn't know that bmat is PSD? Yeah we need to figure out how to assert that it's PSD. Maybe a special atom for lifting complex matrices.

**Comment by rileyjmurray** [comment]
Yes, the issue is that the function `expr.copy([vec, matrix])` is unable to recognize (or at least unstable to exploit) when `matrix.value` is PSD, at least when `matrix` is an Expression. If `matrix` is a Constant, then it correctly recognizes `matrix.is_psd() == True`.

Note: here, `expr` is a `QuadForm` atom.

That said, I ran into an issue when trying to declare a CVXPY Parameter with `lifted_Q1` from my earlier comment. CVXPY said it failed the test for being PSD (even though it's smallest eigenvalue was 8...). I'll write more about this in another ticket so as to not mix topics in this thread.

**Comment by SteveDiamond** [comment]
PSDness of an expression is not determined by looking at expression.value. It's an abstract property propagated via a DCP-like rule system. So the issue is that the bmat expression does not know it is PSD.

**Comment by rileyjmurray** [comment]
Okay. I looked at bmat.py and it's a minimalist wrapper.

It actually brings up a similar issue with kron from #457. One of the great properties of the kronecker product is that if `A` and `B` are PSD, then `kron(A, B)` is also PSD. If you fed a PSD matrix and a PSD CVXPY Variable into my suggested `kron` function, then it would return a CVXPY Expression with unknown curvature.

**Comment by AlanKuurstra** [comment]
@rileyjmurray 

The workaround works here too.  Thanks for your help!

**Comment by rileyjmurray** [comment]
Follow-up: #469 resolved this by adding ``matrix = Constant(matrix.value)`` to the end of the ``quad_canon`` function in ``reductions/complex2real/atom_canonicalizers/matrix_canon.py``. This was somewhat of a hacky fix, because reductions should be performed without accessing any Expression's ``.value`` field (even Expressions that are known to be constant).

In order to implement a proper fix, we need a dedicated Atom that lifts a Hermitian matrix to its real representative. On the face of it such a Hermitian lift (conceptually represented as ``A -> [[re(A), -im(A)],[im(A), re(A)]]``) should be a subclass of the ``bmat`` Atom, with special implementation of ``.is_psd()``. This is not possible because ``bmat.py`` does not define an actual Atom; it's just a wrapper around a bunch of calls to ``vstack`` and ``hstack`` (which *are* Atoms). As a result, implementing the Hermitian lift as an Atom requires that we write ``graph_implementation( ... )``. The ``graph_implementation`` function needs to work with ``LinOp`` objects, and ``LinOp`` objects are deprecated.

If the only way to implement a Hermitian-lift Atom involves increasing cvxpy's dependence on deprecated code, then I think no such Atom should be written. The hacky fix in #469 should stay until dependence on LinOp objects is removed.

@SteveDiamond do you concur? If so then we can close this issue.

**Comment by SteveDiamond** [comment]
@rileyjmurray I believe there is a viable solution within the reductions system. I will take some time and resolve this issue.

**Comment by SteveDiamond** [comment]
I'm cleaning up the issues and I finally resolved this. I made a new class of affine atoms that are essentially no-ops that wrap an atom but assert properties like PSD, positive, etc.
