### ISSUE TITLE
I keep getting error for cvxpy 1.0 on running nosetests

### ISSUE THREAD

**Issue by swagatam101** [cvxgrp/cvxpy#471]
nosetests cvxpy
E
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'LinOp_data_ndim_set')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/software/conda/2.3.0/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/software/conda/2.3.0/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/software/conda/2.3.0/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/rundir/cvxpy/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/rundir/cvxpy/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/rundir/cvxpy/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/rundir/cvxpy/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/rundir/cvxpy/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/rundir/cvxpy/cvxpy/atoms/affine/affine_atom.py", line 25, in <module>
    from cvxpy.CVXcanon.python import canonInterface
  File "/rundir/cvxpy/cvxpy/CVXcanon/python/canonInterface.py", line 32, in <module>
    import cvxpy.CVXcanon.python.CVXcanon as CVXcanon
  File "/rundir/cvxpy/cvxpy/CVXcanon/python/CVXcanon.py", line 229, in <module>
    class LinOp(_object):
  File "/rundir/cvxpy/cvxpy/CVXcanon/python/CVXcanon.py", line 247, in LinOp
    __swig_setmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_set
AttributeError: 'module' object has no attribute 'LinOp_data_ndim_set'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by rileyjmurray** [comment]
This looks like nosetests isn't running in the right directory, or isn't importing from the right directory.

Can you provide additional information on how you setup your development environment? A complete sequence of commands like the following would help a great deal.
```
# OS: Ubuntu 14 "Trusty"
conda create -n testenv --yes python=2.7 mkl pip nose numpy=1.13 scipy=0.19
source activate testenv
conda install -c conda-forge --yes lapack
conda install -c cvxgrp --yes ecos scs multiprocess
conda install -c anaconda --yes flake8
# *** cd into cvxpy directory ***
python setup.py install
nosetests cvxpy
```

**Comment by swagatam101** [comment]
I don't get an error following the exact steps above however, nosetests in testenv gets hung up forever.

**Comment by rileyjmurray** [comment]
It's strange that nosetests are getting hung up on your machine. I just ran the sequence of commands on my personal machine (rather than the remote VM's we use for build tests) and the nosetests ran quickly. Unfortunately, they also failed! Specifically they failed due to an issue with an import error of a numpy module from within CVXcanon.

I think that your original issue, and the one that I experienced are related to out of date source code in CVXcanon. 

In [this TravisCI build](https://travis-ci.org/cvxgrp/cvxpy/jobs/366358128#L1214) between lines 1214 and 1220 there is reference to a deprecated numpy API. You should be able to find similar messages when you install cvxpy on your machine with `python setup.py install` (but only the first time, since that's the only time that CVXcanon is installed). The warnings for the deprecated API come from [CVXcanon_wrap.cpp](https://github.com/cvxgrp/cvxpy/blob/1.0/cvxpy/CVXcanon/python/CVXcanon_wrap.cpp). That file is generated by a program called [swig](swig.org) and isn't automatically re-generated when a user installs cvxpy from source. The current CVXcanon_wrap.cpp was generated with swig 3.0.8. The current version of swig is 3.0.12, and there have been some changes to swig 3.0.9+ that affect imports in Python. 

It might be reasonable to re-build CVXcanon_wrap.cpp with swig 3.0.12, but I'm not sure how much that will actually help. The warning message from the TravisCI build suggests that the issue is the numpy version that swig used for CVXcanon code generation. So it seems to me that the first order of business would be to re-generate CVXcanon code to use an up-to-date numpy API.

@SteveDiamond I'm not familiar with swig or code generation for CVXcanon. Can you make modifications to CVXcanon code generation to use an up-to-date numpy API? The goal here would be that `#warning "Using deprecated NumPy API` does not appear when a user runs `python setup.py install` in an environment with no prior CVXcanon installation.

**Comment by SteveDiamond** [comment]
Ok that of course would be ideal to have no error, but it's not the source of the bug here. As discussed elsewhere you *cannot* install CVXcanon separately with 1.0. You must remove all CVXcanon installations.

**Comment by rileyjmurray** [comment]
Following up on this.

The issue mentioned in my previous comment was due to having multiple CVXcanon installations. I thought that if I installed cvxpy in one virtual environment `env1`, then installations in another environment `env2` would be completely blind to the existence of `env1.` Apparently this is not true.

In my case, although I was switching between virtual environments, I was executing `python setup.py install` in the same directory every time (for completeness I'll say that this directory is `/home/myusername/Documents/Research/cvxpyfork/cvxpy`). I didn't notice until just now, but every time I run the installation command, files are added to a folder called `build` (again in my case, `/home/myusername/Documents/Research/cvxpyfork/cvxpy/build`). Once I deleted this folder and reinstalled, then I experienced @swagatam101's more recent issue : nosetests seemed to hang for a very long time.

That said, the nosetests did eventually run. Only the first few tests were particularly slow. For these tests I looked at my CPU utilization, and almost all 16 cores were at 100%. In my experience, the only time this happens is when a solver is doing multi-threaded matrix operations, but not actually making progress on the overall optimization problem it's trying to solve. This can and does happen with CVXOPT for some exponential cone problems.

@swagatam101 , can you run the nosetests again? This time check your CPU utilization (see if it's high across all cores), and try to let it run for as long as possible.

**Comment by SteveDiamond** [comment]
@rileyjmurray thanks for looking so deeply into this! You're maybe starting to see why conda exists versus just using pip and virtualenv :)

**Comment by akshayka** [comment]
@swagatam101 Can you do pull the most recent changes on 1.0, reinstall CVXPY 1.0, and re-run the steps that resulted in your original issue? d139dbabb58627b5397180060f0942fdcb87e7aa should have solved your problem.
