### ISSUE TITLE
cvxpy dependency fails to compile - no wheels available

### ISSUE THREAD

**Issue by skoudoro** [cvxgrp/cvxpy#503]
Hi @SteveDiamond and CVXPY developers,

Our Travis bots (DIPY) have different issues with `cvxpy` after your last release. We had no issues before.

As you can see [here](https://travis-ci.org/nipy/dipy/jobs/383910399#L756),  building wheel for `osqp` is failing. We got this problem on many bots as you can see [here](https://travis-ci.org/nipy/dipy/builds/383860142?utm_source=github_status&utm_medium=notification)

Any ideas?

**Comment by bstellato** [comment]
It looks like you do not have Python libraries and headers properly installed or that you have multiple python versions. CMake finds the executable but not the libraries and headers with the same version and returns an error.

Could you please try to specify the right variables that the installer needs? Here is an example with a very similar problem: https://stackoverflow.com/a/29657288/9753175

[Here](https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html) they describe how to set those variables in OpenCV.

Wheels are not available because pypi (pip) repositories do not allow it for Linux. If you want precompiled binaries for all the platforms I suggest you to go for anaconda.

**Comment by matthewgilbert** [comment]
I looked into doing this without `conda` but it seems rather involved for `python > 3.4`. The reason is `.so` files are not copied into the virtualenv (I think) as discuseed [here](https://stackoverflow.com/questions/1130402/virtualenv-with-all-python-libraries) and the default travisCI setup does not include the required `python` version.

You can see this from adding `ls` to the `.travis.yml` file. 

```bash
$ python --version
Python 3.5.5

$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (python 3.5)

$ ls -d /usr/include/python*
/usr/include/python2.7  /usr/include/python3.4  /usr/include/python3.4m

$ ls -d /usr/lib/python*
/usr/lib/python2.7  /usr/lib/python3  /usr/lib/python3.4
```

One possible work around would be to a new system wide install of `python` from an external PPA as discussed [here](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get) and then set `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` accordingly but this seems extremely hacky since it depends on creating and using a system wide installation of python which is [not recommended ](https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs)

>> The CI Environment uses separate virtualenv instances for each Python version. This means that as soon as you specify `language: python` in `.travis.yml` your tests will run inside a virtualenv (without you having to explicitly create it). System Python is not used and should not be relied on. If you need to install Python packages, do it via pip and not apt.

I think a better solution would be to move to using conda as discussed by @bstellato however I am currently experiencing issues getting the newest build via `conda` as discussed in #499.

**Comment by gobbedy** [comment]
Woah @matthewgilbert that worked for me too. Thanks!

So
conda install -c conda-forge lapack

should be added to the official install steps

**Comment by skoudoro** [comment]
Thanks for your feedback @bstellato and @matthewgilbert !

> Wheels are not available because pypi (pip) repositories do not allow it for Linux

??? I do not understand this affirmation. Our project has wheel for Linux, opencv or vtk has wheel for Linux as you can see [here](https://pypi.org/project/opencv-python/#files).  What do you mean here @bstellato ?

> but this seems extremely hacky since it depends on creating and using a system wide installation of python which is not recommended

I agree @matthewgilbert, I would like to avoid that

>  If you want precompiled binaries for all the platforms I suggest you to go for anaconda
> I think a better solution would be to move to using conda

We want to make the life easier for our users so it should work with pip AND anaconda, there is no point to force the users to download and use anaconda on linux.... I think, having òsqp wheel on linux seems really important. How can we help for that @bstellato ?  

can you have a look on this thread @arokem, @garyfallidis

**Comment by rileyjmurray** [comment]
@skoudoro

As I understand it: you cannot create python wheels for linux-based operating systems if a project has C dependencies (cvxpy has such dependencies). If you (or anyone on this thread!) thinks otherwise, please let me know. I'm currently working on syncing public deployments with Travis-CI builds, so now is a good time to resolve questions of wheels-vs-eggs-vs-source.

**Comment by arokem** [comment]
I believe that is what the manylinux project is supposed to enable: 

https://github.com/pypa/manylinux

As you can see in the links that @skoudoro provided above, projects such as VTK and OpenCV have adopted this as their practice. It would help downstream dependencies (such as our project) if these wheels could be routinely provided for cvxpy as well. 

Thanks for the great project!

**Comment by Garyfallidis** [comment]
Hi @SteveDiamond, @rileyjmurray , @bstellato and all,

I am not sure I understand here. Are you planning to support a stable pip install for cvxpy or only a stable conda installer? Currently in your travis setup it seems you are only testing with anaconda. As cvxpy is a core module for optimization my suggestion is to provide a stable pip version too. This would definitely be useful for DIPY for example https://github.com/nipy/dipy I am sure there are many other projects with similar needs. It would help immensely if you had another travis bot running with pip and not only conda.

**Comment by Garyfallidis** [comment]
Hi @rileyjmurray,  a few clarifications. We tested the pip installer for cvxpy in a linux machine and it works with no issues. The problem is only with our travis bot. @skoudoro will test to see if adding the include and lib dirs helps the issue. 

Remember that the issue that we have in DIPY's travis bot is "Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3.5")"

As about your question. You can think of continuous integration as a way to check the different tests in your code and make sure everything is passing. But also you can think of ci as a way of checking that your different installers are working in different os versions and operating systems and especially when things are not in order. It seems to me that it would be beneficial to have a travis bot running with a pypi installer in a standard linux environment without anaconda and another one which will be using anaconda. Right now your travis bot is not building at all, only Appveyor is building. You should expect that you still have many users that will run cvxpy in Linux and many of them will not have anaconda installed. Although it is true that more and more people are switching to conda, we still need to support the rest of the cases.

So, let's try to share some experience with the different ci systems used in cvxpy and DIPY. Will get back to you asap about this. We also need to have an anaconda travis bot which we haven't done yet. But let's figure out this issue first.

**Comment by bstellato** [comment]
@Garyfallidis I am trying to build the manylinux wheels for OSQP and it does not seem to be that easy. See https://github.com/oxfordcontrol/osqp-python/pull/5 for more details.

**Comment by matthewgilbert** [comment]
> But also you can think of ci as a way of checking that your different installers are working in different os versions and operating systems and especially when things are not in order. It seems to me that it would be beneficial to have a travis bot running with a pypi installer in a standard linux environment without anaconda and another one which will be using anaconda.

@Garyfallidis Something to keep in mind which I mentioned above is that for TravisCI, the python environments are managed using `virtualenv ` which does not create new shared object files. Also, the TravisCI Ubuntu Trusty machine only comes with `2.7` and `3.4`.

I agree testing pip installing using some appropriately provisioned box with TravisCI would be good, but this doesn't address the issue where downstream users are trying to use `virtualenv` on TravisCI to test their packages which depend on `cvxpy`. This seems like a fundamental issue due to `virtualenv` not creating share objects and TravisCI only having system installs of `2.7` and `3.4`, with no clean solution other than using `conda`. As others have mentioned above it seems like providing a wheels distribution of `cvxpy` could also address this?

**Comment by arokem** [comment]
Yes - I believe that building the manylinux wheel would be helpful for
this! I don't fully understand the issues you face in
oxfordcontrol/osqp-python#
<https://github.com/oxfordcontrol/osqp-python/pull/5>5, but I will try to
take a look.

**Comment by matthew-brett** [comment]
Hi - @arokem pointed me here, because I build a lot of Linux wheels.

I just wanted to check that y'all know that:

* Manylinux wheels always have C extensions, of which Numpy, Scipy and many others, are examples.  Manylinux has a related utility, auditwheel, that finds and vendors all necessary C libraries inside the wheel, as a post-processing step.
* There are a lot of conda users, but there are also a lot of pip users.   I don't know the relevant proportions, but I would venture a guess that the proportion of pip users is not small.  I don't think it's possible to guess yet, whether one will dominate at some point in the future.  As pip distribution improves, it's possible that conda will recede, it's possible it will work the other way.
* CMake can be a problem building Python extensions, because it typically insists on finding a Python library to link to, and, for portable wheels, that's the wrong thing to do.  In particular, on Debian-based distributions, there is frequently no libpython library installed.  See: https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1 for a discussion.  distutils builds, I believe, set compiler flags to allow Python symbols to be resolved at run-time, making the Python library unnecessary (because the extension is running within the Python binary process, where all the relevant symbols are loaded).

See https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/ for more detail, and https://github.com/pypa/manylinux/issues/69 for a related issue.

I'd strongly encourage you to use [multibuild](https://github.com/matthew-brett/multibuild) (warning, I'm the maintainer for that project).  I encourage you because it takes care of some of the machinery you need, and it's widely used (by Numpy, Scipy, Matplotlib etc), therefore, relatively well supported.

**Comment by matthew-brett** [comment]
It's really not too hard to set up the dependencies.   I suppose you mean things like C libraries.  Have a look, for example, at the [Python Pillow recipe](https://github.com/python-pillow/pillow-wheels/blob/master/config.sh) - it just downloads and builds all the libraries it needs in the Manylinux container, then builds the wheel, where the build process detects the libraries automatically.  Finally, (automated by multibuild), `auditwheel` packs all the required C libaries into the wheel, and creates a Manylinux wheel.

I think you'll find that, after a couple of hours of initial investment, you'll have wheel builds automated with a very small ongoing maintenance cost.  I'm very happy to help with multibuild.

I don't think pip users are more computer savvy - pip is the method of installation recommended by the Python Packaging Authority, so many users just assume that it's going to work for them.  Luckily, at the moment, it very often does, but that certainly wasn't true a few years ago, before the widespread distribution of macOS, manylinux and Windows wheels.

I'm going to guess that about half your _potential_ users are using pip.  What will likely happen is they will try and install via pip, it will fail some horrible way that they don't understand, and then they will  give up, and you won't hear from them.

**Comment by Cerebrock** [comment]
matthew is right... walking down that path right now

**Comment by rileyjmurray** [comment]
@Cerebrock , can you be more specific? What is "that path"?

**Comment by demba** [comment]
I'm trying to install cvxpy inside a virtualenv on Ubuntu 16.04 and am getting an error similar to the one that started this thread (see below). I want to check with you guys if the error is related to this thread so I can monitor it and not file a separate ticket. Tks.

    -- Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "3.6" (found /home/me/.pyenv/shims/python3.6)
    -- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3.6")
    CMake Error at CMakeLists.txt:196 (message):
      You need Python libraries to build the Python interface

**Comment by bstellato** [comment]
Yes it is. It is a problem related to OSQP. I will try to fix it in the next days.

**Comment by Garyfallidis** [comment]
Thank you @bstellato that would be fantastic! 👍

**Comment by bstellato** [comment]
New manylinux wheels available on pypi for osqp! https://pypi.org/project/osqp/ Let me know if it fixes the issue.

**Comment by Garyfallidis** [comment]
Congratulations @bstellato! The DIPY developers salute you! We are currently testing your new wheels!!! :tada:

**Comment by skoudoro** [comment]
Awesome ! Thanks a lot @bstellato! I just checked it and everything works like a charm!

Thanks again! I think I can close this issue

**Comment by demba** [comment]
@bstellato, Tks much! Was able to successfully pip install cvxpy in a virtualenv.

Demba.

**Comment by handrew** [comment]
I am also having the same problem mentioned at the beginning of this thread. :( What was the resolution here?

**Comment by bstellato** [comment]
We do not have Python wheels available yet for OSQP in Python 3.7. Many packages haven't been updated to Python 3.7 yet. Can you try with Python 3.6? We will make a new OSQP release soon and it should have Python 3.7 support.

**Comment by handrew** [comment]
Yeah I'm not tied to 3.7, thanks!

**Comment by wkschwartz** [comment]
We are tied to 3.7, so we're looking forward to those OSQP wheels!

Is there anything I can do to work around the problem at the top of this thread in the mean time? We're a pip shop, so switching to conda would be too costly.

**Comment by rileyjmurray** [comment]
@bstellato can you add a source distribution of OSQP to pypi? Right now you only have wheels. 

Although source distributions wouldn't help Windows users much (in that they would need appropriate compilers installed), they would take care of mac and linux users who are in situations like @wkschwartz.

**Comment by wkschwartz** [comment]
cvxpy installs just fine locally on my Mac with pip. Having trouble getting it to work on Travis.

**Comment by bstellato** [comment]
I have just added the source distribution. I will upload the wheels for Python 3.7 very shortly. I am right now waiting for Travis and Appveyor to do their job. They can be very slow when you support many platforms and python versions.

**Comment by bstellato** [comment]
Wheels for python 3.7 for mac and linux should be available. Windows 3.7 still has lots of issues with numpy and scipy and we are not able to build the wheels yet. @wkschwartz Please let me know if the installation works now.

**Comment by wkschwartz** [comment]
Everything works!

Thank you for the help and thank you for doing it so quickly!
