### ISSUE TITLE
GUROBI interface: SolverError returned for infeasible model

### ISSUE THREAD

**Issue by nxtruong** [cvxgrp/cvxpy#521]
An example code of CVXPY with GUROBI:
```python
import numpy as np
import numpy.random as nprand
import cvxpy as cvx

nprand.seed(0)

Q = nprand.randn(2,2) # np.array([[ 1.01092346, -1.246334  ], [-1.246334  , 11.24925237]])
q = np.array([-0.79305302, -0.67245977])
C = np.array([[ 1.74951088, -0.86604018],
       [ 1.83903552,  0.28968686],
       [ 1.85200233,  1.34964664],
       [-0.62858037,  0.15304167]])
c = np.array([ 0.58550308,  0.96431765,  0.40713688, -0.79539809])
z = np.array([ 1.71458648, -1.54797607])

x = cvx.Variable(2)
# obj = cvx.quad_form(x, Q.T @ Q) / 2 + q.T*x + cvx.norm(x-z,2)**2 / 20
obj = cvx.norm(Q*x,2)**2 / 2 + q.T*x + cvx.norm(x-z,2)**2 / 20
constr = [C*x <= c]
prob = cvx.Problem(cvx.Minimize(obj), constr)
prob.is_dcp()
prob.solve(solver=cvx.GUROBI, verbose=True)
```

When I run this code (Python 3.6.5, CVXPY 1.0.5, GUROBI 8.0), GUROBI returns that the model is infeasible:

> Barrier performed 25 iterations in 0.00 seconds
Infeasible model

but CVXPY throws a `SolverError` exception instead of reporting an "Infeasible model" status.
> Traceback (most recent call last):
  File "/Users/tn396/Downloads/testcvx.py", line 22, in <module>
    prob.solve(solver=cvx.GUROBI, verbose=True)
  File "/Users/tn396/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/tn396/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 361, in _solve
    self.unpack_results(solution, self._solving_chain, inverse_data)
  File "/Users/tn396/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 471, in unpack_results
    "to reduce the dynamic range."
cvxpy.error.SolverError: Solver 'GUROBI' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range.
Freed default Gurobi environment

Furthermore, if I use `quad_form` instead of `norm` in the objective function in the above code (see the commented line), which I suppose to be equivalent to the `norm` code, GUROBI has numerical problems in addition to the model being infeasible, while CVXPY still throws the same exception:
> Barrier performed 45 iterations in 0.00 seconds
Numerical trouble encountered

**Comment by SteveDiamond** [comment]
Ok, we need to fix that issue with the infeasible model. Can you see what error code Gurobi is returning? ``quad_form`` is not the same as ``norm**2``. The first gets parsed as a QP, the second doesn't. For the moment we defer numerical issues to the solver developers.

**Comment by nxtruong** [comment]
Some updates:

1. @SteveDiamond Do you know how I can get Gurobi's error code? The text displayed by Gurobi did not mention any error code but said "Infeasible model" as I reported earlier.
2. I don't have OSQP. But I tried with MOSEK and SCS; both reported "infeasible model" (which is correct). But unlike with GUROBI, CVXPY didn't throw a SolverError exception.
3. Some observation:
    - if I use `norm` in the objective, it seems that the problem is cast as an SOCP to both GUROBI and MOSEK.
    - if I use only `quad_form` in the objective, it seems that the problem is cast as a QP to GUROBI but still as an SOCP to MOSEK.

**Comment by rileyjmurray** [comment]
Re:3 

cvxpy converts all QPs to SOCPs before passing to MOSEK. This is done because MOSEK’s QP solver is really an SOCP solver with preprocessing. Rather than do the preprocessing twice (both in mosek and cvxpy), we convert before passing to MOSEK. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gbanjac** [comment]
If you want to get your problem parsed as a QP, you should set your objective as
```
obj = cvx.quad_form(x, Q.T.dot(Q)) / 2 + q.T*x + cvx.sum_squares(x-z) / 20
```
You are getting a `SolverError` because Gurobi returns the status value 4, which means that the problem is either infeasible or unbounded (see [here](http://www.gurobi.com/documentation/8.1/refman/optimization_status_codes.html)), but CVXPY translates this status to `SOLVER_ERROR` (see [here](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py#L29-L43)).

Maybe adding an additional CVXPY status would be a way to solve this issue.

@bstellato OSQP detects infeasibility correctly.
