### ISSUE TITLE
Residual value from constraints

### ISSUE THREAD

**Issue by stevenwong** [cvxgrp/cvxpy#536]
Hi all,

I've originally asked this question in the mailing list but haven't had much luck. The problem is as follows.

I have a problem that can sometimes be infeasible. The desired behaviour is to relax the constraint that was violated and continue, but alert the user that XYZ was violated.

I noticed that CVXPY 1.0 has a new violation() method that calculates the residual of the constraint (https://www.cvxpy.org/api_reference/cvxpy.constraints.html), but when the problem was infeasible, the constraint doesn't look like it's calculated?

Using the example on the front page:

```
In [15]:
import cvxpy as cp
import numpy as np

# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x, x <= 1, x >= 2]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)
None
None

In [16]:

In [16]: prob.status
Out[16]: 'infeasible'

In [17]: prob.constraints
Out[17]:
[NonPos(Expression(AFFINE, UNKNOWN, (20,))),
 NonPos(Expression(AFFINE, UNKNOWN, (20,))),
 NonPos(Expression(AFFINE, UNKNOWN, (20,)))]

In [18]: prob.constraints[0]
Out[18]: NonPos(Expression(AFFINE, UNKNOWN, (20,)))

In [19]: prob.constraints[0].violation()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-5ce1fdea8037> in <module>()
----> 1 prob.constraints[0].violation()

C:\Program Files\Anaconda3\envs\py35\lib\site-packages\cvxpy\constraints\constra
int.py in violation(self)
    137         residual = self.residual
    138         if residual is None:
--> 139             raise ValueError("Cannot compute the violation of an constra
int "
    140                              "whose expression is None-valued.")
    141         return residual

ValueError: Cannot compute the violation of an constraint whose expression is None-valued.
```

How do you get the residual, or check which constraint was violated, or get the last tried solution so I can test which constraint failed?

Cheers,
Steve

**Comment by rileyjmurray** [comment]
Hi Steve; thanks for posting.

In order to calculate the violation for a constraint, we need a value for the problem's decision variables. The problem is that when a solver reports that a problem is infeasible, it won't return *any* values for the decision variables (even ones that are "nearly feasible"). This is part of the nature of constrained optimization problems- it's very rare to say that a single constraint is "responsible" for infeasibility. The closest thing you can find is an infeasibility-diagnostic tool like that found in MOSEK (and likely other commercial solvers). Unfortunately diagnostic tools can be a pain to understand, especially when using a rewriting system such as cvxpy.

The purpose of the .violation() method is not to investigate infeasibility issues, but instead to address the fact that optimization in finite precision is an inexact science. Sure, a constraint like `x <= 0` can be satisfied strictly, but a constraint like `Ax == b` is bound to have some residual error (even when A is invertible). In practice users should expect .violation() to return very, very small numbers. A good interior point solver like MOSEK will often have the largest constraint violation be on the order of 1e-8. However first order solvers (like SCS) are notorious for returning solutions with much higher constraint violations (e.g. 1e-4).

Please post again if I misunderstood you.
