### ISSUE TITLE
Expression .value returns scalar when it should be a 1x1 matrix.

### ISSUE THREAD

**Issue by acristoffers** [cvxgrp/cvxpy#543]
I don't work with LMI myself, but I was asked for help on something that I think may be a regression introduced in version 1.0, because the people working with it say it worked fine before.

They declare some variables like `R = cp.Variable((m,m), diag=True)` (it was `R = cp.diag(cp.Variable((m,m)))` before). But `m=1`, so it's a 1x1 matrix.

They later use

```
m55 = -2*R
...
LMI1 = cp.vstack([cp.hstack([m11, m12, m13, m14, m15, m16]),
            cp.hstack([m21, m22, m23, m24, m25, m26]),
            cp.hstack([m31, m32, m33, m34, m35, m36]),
            cp.hstack([m41, m42, m43, m44, m45, m46]),
            cp.hstack([m51, m52, m53, m54, m55, m56]),
            cp.hstack([m61, m62, m63, m64, m65, m66])])
```

and then use it to solve the problem, which works. But to see if the solution is satisfied, they need to do `np.linalg.eigvals(np.mat(LMI1.value + np.eye(LMI1.shape[1])*eps))`, which gives an error because m55 is a 1x1 matrix but `m55.value` returns a scalar, so cp.hstack can't concatenate (the other matrices are, I think, 1x3).

Shouldn't there be a way to say that the expression is to be a matrix no matter what? Right now we are rebuilding this matrix and reshaping like this:

```
LMI1 = cp.vstack([cp.hstack([m11, m12, m13, m14, m15, m16]),
            cp.hstack([m21, m22, m23, m24, m25, m26]),
            cp.hstack([m31, m32, m33, m34, m35, m36]),
            cp.hstack([m41, m42, m43, m44, m45, m46]),
            cp.hstack([m51, m52, m53, m54, m55.value.reshape(m,m), m56]),
            cp.hstack([m61, m62, m63, m64, m65, m66])])
```

but I have the feeling this is a workaround, not a solution. But I might be wrong, as I don't work with LMIs.

A gist with full file: https://gist.github.com/acristoffers/f499a9ca29ed160b1612166be78b061f

**Comment by rileyjmurray** [comment]
The issue is unrelated to ``R`` being diagonal.

The example code below shows that...
* when ``R`` is a 1-by-1 CVXPY Variable, ``R.value`` will be a 1-by-1 numpy array (when it is defined).
* when ``otherR = -2 * R`` (for a 1-by-1 CVXPY Variable ``R``), we will have ``otherR.shape == R.shape``, but ``otherR.value`` will be a scalar. 

```
(dev35) [rmurray@localhost cvxpyfork]$ python
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:41:05) 
>>> import cvxpy
>>> print(cvxpy.__version__)
1.0.6
>>> R = cvxpy.Variable(shape=(1,1))
>>> obj = cvxpy.Minimize(R)
>>> constrs = [R == 1]
>>> prob = cvxpy.Problem(obj, constrs)
>>> prob.solve(solver='ECOS')
0.9999999999999951
>>> R
Variable((1, 1))
>>> R.value
array([[1.]])
>>> otherR = -2 * R
>>> otherR
Expression(AFFINE, UNKNOWN, (1, 1))
>>> otherR.value
-1.9999999999999902
>>> otherR.shape
(1,1)
>>> R.shape
(1,1)
```

At the coarsest level, ``otherR`` and ``R`` are cvxpy Expressions.
At the finest level
*  ``R`` is a ``Variable(Leaf(Expression))``.
* ``otherR`` is a ``multiply(MulExpression(BinaryOperator(AffAtom(Atom(Expression)))))``
So ``R.value`` is implemented in ``variable.py``, while ``otherR.value`` is implemented in ``atom.py``.
The difference appears on line 243 of ``atom.py``, where it casts 1-by-1 values to scalars.

I'm not sure how to proceed from here. I mean, obviously we *could* remove the casting in atom.py, but there are pros and cons to that.

**Comment by rileyjmurray** [comment]
I think the best way to handle this would be to *remove* the default conversion of 1-by-1 arrays to scalars, at least at the level of atom.py.

The conversion to scalar does seem appropriate in the more restricted setting of calling ``.value`` on a cvxpy Problem or Objective. The conversion can easily be implemented by changing the accessors defined on lines 85 and 93 of ``problem.py`` and ``objective.py`` respectively.

@SteveDiamond , what are your thoughts?

**Comment by SteveDiamond** [comment]
@rileyjmurray I agree with removing the default conversion of 1-by-1 arrays to scalars. It's a relic from when everything was 2D, so scalars and 1-by-1 arrays were the same thing.

**Comment by rileyjmurray** [comment]
I've made this change on my fork of cvxpy; it'll be part of my next pull request.
