### ISSUE TITLE
Incorrect solution to simple ILP problem

### ISSUE THREAD

**Issue by SeanRBurton** [cvxgrp/cvxpy#578]
The following Python3 program:

```
import numpy as np
import cvxpy

v = np.array([-1, -1])
m = np.zeros((2, 2))
selection = cvxpy.Variable(2, boolean=True)
constraint = m @ selection <= v
problem = cvxpy.Problem(cvxpy.Minimize(0), [constraint])
print(problem.solve())                        
```

should surely not find a feasible solution, but it prints `0.0`. Maybe I'm missing something?

**Comment by SteveDiamond** [comment]
Yes, it seems best to not have ECOS_BB as a default. It might even be best to not have any default integer solver at all, and if the user tries to solve an integer program cvxpy tells them to install one of various options.

**Comment by rileyjmurray** [comment]
Okay cool. Sometime soon I'll look into things a bit more just to be sure that the issue with ECOS_BB isn't because of some crazy canonicalization thing happening within cvxpy. 

I don't really like the idea of not having a default integer programming solver. Are there licensing issues to making GLPK a dependency of cvxpy?

**Comment by rileyjmurray** [comment]
I have confirmed that the error is due to ECOS_BB, and not something on cvxpy's end; I've opened up a ticket https://github.com/embotech/ecos/issues/166 on the ECOS page.
