### ISSUE TITLE
Problems migrating from 0.4 to 1.0

### ISSUE THREAD

**Issue by almendezuc3m** [cvxgrp/cvxpy#586]
I was working with cvxpy 0.4 version, and in this version I had programmed the group lasso penalized linear model as follows:

```
from cvxpy import *
from sklearn.datasets import load_boston
import numpy as np
boston = load_boston()
x = boston.data
y = boston.target
index = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5])
lambda_val = 1
```
### 0.4 version
```
n = x.shape[0]
lambda_param = Parameter(sign="positive")
index = np.append(0, index)
x = np.c_[np.ones(n), x]
group_sizes = []
beta_var = []
unique_index = np.unique(index)
for idx in unique_index:
    group_sizes.append(len(np.where(index == idx)[0]))
    beta_var.append(Variable(len(np.where(index == idx)[0])))
num_groups = len(group_sizes)
group_lasso_penalization = 0
model_prediction = x[:, np.where(index == unique_index[0])[0]] * beta_var[0]
for i in range(1, num_groups):
    model_prediction += x[:, np.where(index == unique_index[i])[0]] * beta_var[i]
    group_lasso_penalization += sqrt(group_sizes[i]) * norm(beta_var[i], 2)
lm_penalization = (1.0 / n) * sum_squares(y - model_prediction)
objective = Minimize(lm_penalization + (lambda_param * group_lasso_penalization))
problem = Problem(objective)
lambda_param.value = lambda_val
problem.solve(solver=ECOS)
beta_sol = [b.value for b in beta_var]
```
### 1.0 Version
```
n = x.shape[0]
lambda_param = Parameter(nonneg=True)
index = np.append(0, index)
x = np.c_[np.ones(n), x]
group_sizes = []
beta_var = []
unique_index = np.unique(index)
for idx in unique_index:
    group_sizes.append(len(np.where(index == idx)[0]))
    beta_var.append(Variable(shape=(len(np.where(index == idx)[0]), 1)))
num_groups = len(group_sizes)
model_prediction = 0
group_lasso_penalization = 0
model_prediction = x[:, np.where(index == unique_index[0])[0]] * beta_var[0]
for i in range(1, num_groups):
    model_prediction += x[:, np.where(index == unique_index[i])[0]] * beta_var[i]
    group_lasso_penalization += sqrt(group_sizes[i]) * norm(beta_var[i], 2)
lm_penalization = (1.0 / n) * sum_squares(y.reshape((n, 1)) - model_prediction)
objective = Minimize(lm_penalization + (lambda_param * group_lasso_penalization))
problem = Problem(objective)
lambda_param.value = lambda_val
problem.solve(solver=ECOS)
beta_sol = [b.value for b in beta_var]
```
While using the 1.0 code version, it shows this error message:
![image](https://user-images.githubusercontent.com/43582258/46081418-bde8a700-c19c-11e8-9da2-10a95b14e598.png)

So the problem I find is that solving this problem with ECOS solver worked fine in 0.4 version, but it fails in 1.0 version. Is it due to some thing I missed to change? is it due to something working differently in the module after the update?

**Comment by SteveDiamond** [comment]
The issue is that the ``norm(beta_var[i], 2)`` is being interpreted as a matrix norm. For now change it to ``norm(beta_var[i], 'fro')``. I need to think about this issue.

**Comment by rileyjmurray** [comment]
@SteveDiamond we made this change because for nx1 and 1xn vectors, the matrix 2 norm is the same as the vector 2 norm. But since the matrix 2-norm is generally represented with linear matrix inequalities, cvxpy says that ECOS can't handle it.

This might seem odd, but one solution would be to change the behavior of the canonical form for the matrix 2-norm when the matrix is nx1 or 1xn. Instead of relying on linear matrix inequalities, it could use an equivalent SOCP formulation. 

A more general approach would be to add a reduction that simplifies [block] 2-by-2 linear matrix inequalities into equivalent SOCP constraints. Of course, doing this would be much more complicated.

@almendezuc3m you can also use ``norm(beta_var[i], 2)``, as long as you define ``beta_var[i]`` to have ``len(beta_var[i].shape) == 1``.

**Comment by SteveDiamond** [comment]
I changed norm so it always uses SOCPs for (n,1) or (1,n) shapes.
