### ISSUE TITLE
Advice on optimal_inaccurate?

### ISSUE THREAD

**Issue by apryor6** [cvxgrp/cvxpy#595]
I have an optimization application for allocating a total number of units. For some values of this total the solution produced is "optimal" and for others it is "optimal_inaccurate". The optimal_inaccurate solutions are correct but take longer to calculate. Does anybody have some generic comments or insights about the meaning of solutions labeled optimal_inaccurate?

**Comment by rileyjmurray** [comment]
This is a better question for stackexchange with a cvxpy tag, but I'll give my 2 cents:

Most solvers have their own criteria for when a solution is reported as "optimal" versus when a solution is reported as "optimal / inaccurate". These criteria are not universally comparable across solvers, because different solvers use entirely different ways to estimate the error or optimality gap of a solution.

In some cases "optimal / inaccurate" can mean that the solution violates constraints slightly more than you would expect from ordinary round-off error with finite precision arithmetic. In other cases it may mean that you are getting a feasible solution, but the solver has not ruled out the possibility of a [nontrivially] better solution existing.

In practice, when you get "optimal / inaccurate", you should verify that the returned solution satisfies your constraints within the precision needed for your application. If your application is data science / machine learning driven, then slight violation of constraints may not be cause for concern. If instead you are solving a problem which designs a rocket engine, then you should probably be very picky about when you actually use an "inaccurate" solution.

As a side-note, "optimal / inaccurate" solutions take longer to calculate because the solver doesn't *want* to have to return that value. So it is not that inaccurate solutions necessarily take longer to compute, but rather that when a solver is struggling, it is more likely to eventually give up and return a solution with the "inaccurate" flag.
