### ISSUE TITLE
Non-deterministic output

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/cvxpy#614]
Failing test case is given here.

https://github.com/dave31415/cvxpy_deterministic_fail

**Comment by rileyjmurray** [comment]
I took a look at your example. Here is what I found:

(1) There are only two values that cvxpy ever returns. The original value, and another value that differs from the original by 1e-11. 

(2) The problem that cvxpy is passing to ECOS is identical in both situations. You can access the solver data with 
```
prob = model.problem
data = prob.get_problem_data('ECOS')
G, h, c = data[0]['G'], data[0]['h'], data[0]['c']
G = G.todense()
```
When I say that cvxpy passes the same data to ECOS, I mean that ``np.linalg.norm(G_orig - G_new) == 0`` (and similarly for ``h``, ``c``).

Here are my conclusions:

(1) The problem data handed to ECOS is identical in both cases, so any "nondeterminism" seems to be stemming from computations performed in ECOS. Handling such behavior is beyond the scope of cvxpy's development.
(2) The objective value difference is so small (1e-11 absolute error, 1e-15 relative error) that this doesn't seem to be a practical issue; I don't think the developers of ECOS would want to put effort into investigating why this is happening.
(3) If someone wants to check determinism on cvxpy's end, they should compare the raw problem data (such as G, h, c for your model in ECOS) rather than the objective value returned by the solver.

I am closing this issue for now. If you notice non-determinism that violates point (3) above, then feel free to re-open the issue.

**Comment by dave31415** [comment]
Hi. Thanks. For looking into this. Forgot to mention that if you use
CVXOPT, it gets similar non-deterministic behavior. Just change line 13 to
"CVXOPT". Wouldn't that imply that it has to be CVXPY or one of it's
dependencies?

David Johnston
Principal Data Scientist, ThoughtWorks
dajohnst@thoughtworks.com
c: 773 600-9417
LinkedIn <https://www.linkedin.com/in/david-johnston-a0b84436>

**Comment by dave31415** [comment]
Actually the problem data is not always the same either. The c variable
seems to be changing. That doesn't always solve the problem though. There
are cases where the data does not change but output still does change.

Hash for c: 261950133
[  1.   1.   1.   1.   1.   1.   1.   1. 120. 120.   0.   0.   0.   0.]
Hash for offset: 524289
Hash for G: 1869960053
Hash for h: 3586658007
HASH_VAL_ITER_18: ce4910b814eb70bdc1b6
HASH_DATA_ITER_18: d47f7238b6753fb5
Input data has changed
Fit model appears to be non-deterministic on iter 19
-------------------------
Hash for c: 3947760309
[  1.   1.   1.   1. 120. 120.   1.   1.   1.   1.   0.   0.   0.   0.]


David Johnston
Principal Data Scientist, ThoughtWorks
dajohnst@thoughtworks.com
c: 773 600-9417
LinkedIn <https://www.linkedin.com/in/david-johnston-a0b84436>

**Comment by dave31415** [comment]
I pushed some changes showing that the get_problem_data returns are also
non-deterministic.
https://github.com/dave31415/cvxpy_deterministic_fail

David Johnston
Principal Data Scientist, ThoughtWorks
dajohnst@thoughtworks.com
c: 773 600-9417
LinkedIn <https://www.linkedin.com/in/david-johnston-a0b84436>

**Comment by dave31415** [comment]
Note that if you change the use_hinge variable to False (line 172), it
passes. This leads me to believe that there is something non-deterministic
about adding objective terms together.

David Johnston
Principal Data Scientist, ThoughtWorks
dajohnst@thoughtworks.com
c: 773 600-9417
LinkedIn <https://www.linkedin.com/in/david-johnston-a0b84436>

**Comment by dave31415** [comment]
In light of the above, can you reopen this issue?

**Comment by rileyjmurray** [comment]
Dang! That's some good digging you did there @dave31415. Yes this should be looked into more.

**Comment by SteveDiamond** [comment]
This is fixed in master thanks to Bart.
