### ISSUE TITLE
data scaling issue: stopping criteria are not scale-invariant?

### ISSUE THREAD

**Issue by lobpcg** [cvxgrp/cvxpy#681]
**Describe the bug**
Solving Ax=b without constraints is sensitive to scaling of A and b by a small constant, i.e., solving (aA)x=(ab) is not a-invariant. Specifically, for small values the solver fails or, worse, gives wrong answers without any warnings,  e.g., `a = 1e-5` and smaller, although works fine for very large values, e.g., `a = 1e10` and even larger. 

Apparently related to https://github.com/cvxgrp/cvxpy/issues/261 and https://groups.google.com/forum/#!searchin/cvxpy/scale|sort:date/cvxpy/BOq4SF_zUh4/FNjuev2nDgAJ

**To Reproduce**
Vary the value of `a` below:

```
from cvxpy import *
import numpy

# Problem data.
m = 20
a = 1e-5
numpy.random.seed(1)
A = a*numpy.random.randn(m, m)
b = a*numpy.random.randn(m)
  
# Construct the problem.
x = Variable(m)
objective = Minimize(sum_squares(A*x - b))
prob = Problem(objective)

sol_linear = numpy.linalg.solve(A, b)
print(sol_linear)

# The optimal objective is returned by prob.solve().
result = prob.solve()
# The optimal value for x is stored in x.value.
print(x.value)
```

**Expected behavior**
The exact solution `x` is mathematically `a`-invariant, as well as the approximate solution by numpy.linalg.solve. The CVXPY solution `x` should be also  `a`-invariant within a reasonable range of `a`. When the solution is wrong, it would be nice to have a warning.

The issue may be that the stopping criteria are not scale-invariant? Does  CVXPY processing include some automatic scaling? 

**Output**
The first vector is the numpy.linalg.solve solution. 
The second vector is the CVXPY solution, may be no warnings. 
 
from a = 1e-3 to  a = 1e10

[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]
[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]

a = 1e-5

[13.81646443  3.66409028  2.79760942  4.81443112  8.0037291  -1.08660789
  6.16723623 -4.74334805  4.59619346 15.25835196 -3.99358756  9.86669114
  0.02746706  0.11107449 -5.08887493 -8.30233997  7.13619748  8.58846973
 -1.65658374 -7.94297172]
[-0.00479387  0.00808702  0.00372401 -0.00262185 -0.0017977   0.0017227
 -0.0015533   0.0005133   0.00970509 -0.00645568 -0.0002975   0.00171565
 -0.00029209  0.00749652 -0.0049597  -0.0065485   0.00451802  0.00176061
  0.00137181 -0.00043657]

**Version**
 - OS: Python 3.7.0 64bit for Win 10
 - CVXPY Version: cvxpy-1.0.19

**Additional context**
I have intentionally chosen a rather trivial example. The trouble may get worse for practically interesting cases.  

I am new to CVXPY, so apologize in advance if I miss something trivial here...

**Comment by rileyjmurray** [comment]
Thank you for posting detailed information. It is important to note that CVXPY is not a solver. It is a rewriting system / compiler, that enables a user to specify a model in natural terms while still invoking high performance numerical solvers. The numerical solvers in question (e.g. ECOS, SCS, OSQP, MOSEK, GUROBI, etc...) all have their own stopping criteria.

These stopping criteria try to be scale-invariant, but they will always be limited by the precision of the standard ``double`` datatype in C. The ``double`` datatype only reliably represents numbers to tolerance ``1e-16``. In order for optimization solvers to check stopping criteria, they need to multiply double-precision numbers. Therefore in order for solvers to accurately compute the stopping criteria, the input values must be larger than ``1e-8`` in magnitude.

In your example, setting ``a = 1e-8`` will cause essentially any underlying solver to fail without automatic problem rescaling. In fact, since the optimal solution for your problem contains terms on the order of ``1e-1``, you will find that any solver is bound to fail when ``a`` is less than ``1e-7``. Your case you have shown that the default solver (OSQP) fails when ``a  <= 1e-5``. If you try the ECOS solver, you will see that it only fails for ``a  =< 1e-7``. 

Automatic rescaling would be a nice feature for CVXPY, but I don't think it's a high-priority item for us at the moment. We believe that it is reasonable to ask that users specify their problems in a way that reflects an awareness of finite-precision arithmetic on digital computers. If users don't want to perform problem scaling themselves, then they should try using the commercial solvers accessible through CVXPY (MOSEK, GUROBI, CPLEX, etc...). Those commercial solvers are more likely to have aggressive presolve and rescaling features.

**Comment by lobpcg** [comment]
Thanks for your quick and detailed reply!

**Comment by bstellato** [comment]
For the record, you can get the right solution with OSQP by using the line
```python
prob.solve(solver='OSQP', verbose=True, scaling=20)
```

For more details see https://github.com/oxfordcontrol/osqp/issues/120#issuecomment-469411966
