### ISSUE TITLE
Hard dependencies and fixed version

### ISSUE THREAD

**Issue by ismailb0** [cvxgrp/cvxpy#696]
Hello!

I’ve been using cvxpy on a project and recently noticed that we had the following error while installing the project:

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sjhxbig1/scs/
```
After looking into it, we found that there was a new release of scs earlier that week and that for some reason that new version breaks the installation of our requirements.

Moreover, we found out that cvx requires a `scs >= 1.1.3`, which means that if I don’t already have any scs version, the latest one (that breaks in our case) will be installed.

To solve that, we manually added `scs==1.2.7` to our requirements.txt before cvx so that when installing cvx the requirement is considered already up-to-date.

My questions are:

* Is there a specific reason why scs version in cvx is not fixed to a specific version? Wouldn’t we want to keep a version that we know works well and just update it manually whenever needed?
* Why is scs a hard requirement in the first place? Wouldn’t we want the user to add to his requirements the solver he wants to use so that he doesn’t have to install all of them? In our case, we only use ecos and spent some time dealing with a scs installation error.

What are your thoughts about that? :)

**Comment by SteveDiamond** [comment]
That's unfortunate the new SCS breaks your installation. It would be undesirable though to require fixed builds, because then it would be impossible to use CVXPY with the latest versions of solvers. It also does not seem necessary. You could have fixed your problem by installing SCS first.

As for why SCS is a requirement at all, we've had a lot of debate about this but I feel it's worth it. Many users actually don't know a single thing about solvers, and even believe CVXPY solves the problem. Asking them to install solvers is too much.
