### ISSUE TITLE
can't use cvxpy transforms.indicator

### ISSUE THREAD

**Issue by nunatic222** [cvxgrp/cvxpy#722]
when trying the example code on website 
( I've created a file called example.py containing code below)
```
import cvxpy as cp
x = cp.Variable()
constraints = [0 <= x, x <= 1]
expr = cp.transforms.indicator(constraints)
x.value = .5
print("expr.value = ", expr.value)
x.value = 2
print("expr.value = ", expr.value)
```
I always got
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    expr = cp.transforms.indicator(constraints)
TypeError: Can't instantiate abstract class indicator with abstract methods is_log_log_concave, is_log_log_convex
```

**About my OS and installation method**
 - OS:  I've tried on MacOS Mojave, MacOS High Sierra, Ubuntu 16.04

 I firstly tried on MacOS Mojave. After struggling with this problem and got no result, I re-installed MacOS High Sierra and got the same error output. I then turned to Ubuntu 16.04 and got the same error output.

 - CVXPY Version: 1.0.21
 - python Version: 2.7.10, 3.7.3 both tried

 - Installation method:

**I've tried below methods for installation on every operating system above.**

 **1. Creating a conda environment within pycharm, and install cvxpy there.
And then run the program within pycharm.**

After getting such TypeError, I turned to create a new anaconda environment in Terminal, and ran the program in the terminal.

 **2. Installing cvxpy with anaconda:**

```
conda config --add channels oxfordcontrol
conda install -c conda-forge lapack
conda install -c cvxgrp cvxpy=1.0.21
```
Then create a new environment:
```
conda create -n Example python = 3.7 anaconda
```
Then run the program:
```
python3 example.py
```
After getting such TypeError again, I turned to install with pip.
 
**3. Installing with pip:**

(on MacOS, I've tried
```
pip install --user cvxpy
```
Got the same TypeError, I then tried
```
pip3 install --user cvxpy
```
Hoping that using python3 will get rid of such error.
But that didn't work.

On Ubuntu, I used
```
pip install cvxpy
```
```
pip3 install cvxpy
```

**Comment by superobertking** [comment]
This issue seems to come from this [commit](https://github.com/cvxgrp/cvxpy/commit/1316ce16cc49287ea216c0e421fded18942fb9bd#diff-82e7f00899ffe8e8b76473d64f2178ffR214). The `is_log_log_convex` and `is_log_log_concave ` functions are marked as `abstractmethod` in `Expression` class. However, the [`indicator`](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/transforms/indicator.py) class, which derives from `Expression` class, did not implement `is_log_log_concave` and `is_log_log_convex `. Scrolling back to an older version on my computer seems to temporarily solve the problem.

**Comment by akshayka** [comment]
This issue is fixed at master, and it will be fixed in the next release of CVXPY.
