### ISSUE TITLE
Python 2.7 End-of-Life Policy

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#739]
We should come up with a policy for the end of life of Python 2.7, i.e., we should decide when we'll stop supporting 2.7, and we should communicate this decision to our users.

For example, we might decide to only support Python 3 for versions 1.10 onwards. That would mean dropping 2.7 support sometime late summer or early autumn.

**Comment by SteveDiamond** [comment]
I vote for ending Python 2.7 support with 1.1.0. NumPy and SciPy ended support by putting up nice 2.7 builds, so that could be a subgoal. Someone in our group is working on getting proper SCS conda builds for Windows, so we could try and get everything in order with conda before we stop putting out new 2.7 builds.

**Comment by rileyjmurray** [comment]
I vote for ending Python 2.7 support with cvxpy version 1.1. Builds and deployment are only going to become harder and harder as cvxpy dependencies move on from Python 2.7.

**Comment by akshayka** [comment]
Okay, it's official --- I've updated the README. We'll drop Python 2.7 support starting with 1.1.
