### ISSUE TITLE
DQCP Product Issue

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#768]
**Describe the bug**
[This page](https://www.cvxpy.org/tutorial/dqcp/index.html) says 
>  The scalar product * is quasiconvex when one of its arguments is nonnegative and the other is nonpositive, and it is quasiconcave when its arguments are both nonnegative or both nonpositive. Hence, the product of two nonnegative quasiconcave functions is quasiconcave, and the product of a nonnegative concave function and a nonpositive convex function is quasiconvex.

Consider the following code:
```python
#!/usr/bin/env python3
import cvxpy as cp

x = cp.exp(cp.Variable(pos=True))
y = cp.exp(cp.Variable(pos=True))
p = cp.multiply(x, y)
x
y
assert p.is_dqcp()
```
which gives output:
```
>>> x
Expression(CONVEX, NONNEGATIVE, ())
>>> y
Expression(CONVEX, NONNEGATIVE, ())
```
Based on the description on the page the scalar product "**is quasiconcave when its arguments are both nonnegative**".

**Expected behavior**
`x` and `y` satisfy the condition listed, but the result is not DQCP. `x` and `y` also seem to satisfy the more formal conditions listed higher on the page.

**Version**
 - OS: Ubuntu 18.04.2 LTS
 - CVXPY Version: 1.0.24

**Additional context**
I think either the disciplined evaluator or the textual description has a mistake.

**Comment by akshayka** [comment]
Hey Richard — thanks for writing up your issue so clearly.

The scalar product atom, *, is quasiconcave when its arguments are nonnegative. This means that x * y is quasiconcave when x and y are nonnegative. So exp(x) * exp(y) is quasiconcave in x’ = exp(x) and y’ = exp(y), but not necessarily in x and y. In particular, exp(x) * exp(y) doesn’t satisfy the composition rule because x*y is quasiconcave and increasing in its arguments (when they are nonnegative), but exp(x) and exp(y) are convex. On the other hand, you’ll find that sqrt(x) * sqrt(y) is correctly parsed as quasiconcave.

Does that make sense?

**Comment by r-barnes** [comment]
Thanks. If I follow you correctly, this problem (product of non-negative convex forms) cannot be translated into a quasiconvex form. I believe this makes sense, but it takes some squinting at the documentation to find that argument. Perhaps a counter-example there would make it clearer.

**Comment by akshayka** [comment]
Yes, that's correct. I've added a small clarification to the documentation, which should be reflected on the website within a few days.
