### ISSUE TITLE
Possible incorrect solution for SDP with complex variables

### ISSUE THREAD

**Issue by joshcombes** [cvxgrp/cvxpy#813]
**Describe the bug**
The code below solves the SDP correctly in some cases. On some problems we are seeing large discrepancies between CVXPY and CVX (called from matlab). We have good reasons to believe the matlab code. 

**To Reproduce**

First we import and load some test cases: 
```python
# Download pickle here: 
# https://www.dropbox.com/sh/j7045mtxk0evl5n/AACx6B26hCOstF5QHHsnBoOWa?dl=0

import pickle

with open('sdp_data.pickle', 'rb') as f:
    data = pickle.load(f)

# load problems and matlab solutions as a list of np.arrays
input_matrix = [data.get('C1'), data.get('C2'), data.get('C3')]
matlab_cvx_answer = [data.get('X1'), data.get('X2'), data.get('X3')]
p_dim = data.get('pdim')
c_dim = data.get('cdim')
```
Now use a function to define the SDP and import helper functions:
```python
import numpy as np
import cvxpy as cp
from typing import Union
import scipy.sparse as sps

# Download this helper from:
# https://www.dropbox.com/s/4uhrdodobry3b7k/_cvxpy_partial_trace_helper.py?dl=0
# it is from https://github.com/cvxgrp/cvxpy/issues/563
from _cvxpy_partial_trace_helper import cvxpy_partial_trace

def cvxpy_sdp(C: Union[np.ndarray, sps.csr_matrix], phdim: int, codim:int):
    dim = phdim * codim
    assert(C.shape == (dim, dim))
    
    X = cp.Variable((dim, dim), complex=True)

    constraints = [cvxpy_partial_trace(X, [pdim, cdim], axis=1) == np.eye(pdim)]
    constraints += [X >> 0]   # PSD 
    constraints += [X.H == X] # Hermitian
    
    obj = cp.Maximize( cp.real( cp.trace(X*C) ) )
    prob = cp.Problem(obj, constraints)
    prob.solve()
    return X, prob
```

Loop over three problems and compare CVXPY to cvx:
```python
for C, Xmatlab, pdim, cdim in zip(input_matrix, matlab_cvx_answer, p_dim, c_dim):
    # solve the SDP
    X, prob = cvxpy_sdp(C, pdim, cdim)
    # see how close
    print('allclose', np.allclose(X.value, Xmatlab, atol=1e-07))
    print('max(abs(X-Xmat))',np.max(np.abs(X.value - Xmatlab)))
    print('')
```
**Expected behavior**
The expected behavior is given by the matlab solution. We would like them to agree to 1e-7 plus or minus an order of magnitude. 

**Output**
```
allclose False
max(abs(X-Xmat)) 0.5000000001251502

allclose False
max(abs(X-Xmat)) 0.9988953132692987

allclose False
max(abs(X-Xmat)) 0.9814188020644817
```

**Version**
 - OS:  OSX 10.14.6
 - CVXPY Version: 1.0.24
 - Python: 3.7.3
 - Numpy: 1.16.5

**Additional context**

**Comment by joshcombes** [comment]
fyi the matlab SDP solver is

```
function R=cvxsdp(C, pdim, cdim)

physdim = double(pdim);
codedim = double(cdim);
dim = codedim*physdim;

C = reshape(C, dim, dim);

cvx_begin sdp quiet
    variable X(dim, dim) hermitian
    maximise real(trace(X*C))
    subject to
        X >= 0;
        TrX(X, [2], [physdim, codedim]) == eye(physdim);
cvx_end

R = full(X);
```

where the function `TrX` can be found here http://www.dr-qubit.org/matlab/TrX.m

**Comment by rileyjmurray** [comment]
Using
```
C, Xmatlab, pdim, cdim = input_matrix[0], matlab_cvx_answer[0], p_dim[0], c_dim[0]
mlpt = cvxpy_partial_trace(Xmatlab, [pdim, cdim], axis=1)
```
I get ``mlpt.value`` is about ``6 * np.eye(pdim)``. Meanwhile, your cvxpy constraint is that ``cvxpy_partial_trace(X, [pdim, cdim], axis=1) == np.eye(pdim)``. So from the perspective of the cvxpy Problem, the Matlab solution is infeasible by a very wide margin.

This likely means the cvxpy problem you formulated didn't match the Matlab problem you formulated. Specifically, it seems plausible that``cvxpy_partial_trace`` might not behave in the same way as ``TrX`` from the matlab script. Please investigate these differences further.

If you believe the unofficial cvxpy partial-trace helper function is incorrect, we welcome a comment on issue #563. I'm going to close this issue for now, since I believe official CVXPY functions are behaving correctly.

Note: to call ``cvxpy_partial_trace`` on a numpy ndarray, you may need to edit line 60 of `` _cvxpy_partial_trace_helper.py`` to be ``rho = cvxpy.Constant(value=rho)``. I got a runtime error when using the current line ``rho = cvxpy.Constant(shape=rho.shape, value=rho)``.
