### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by JudsonWilson** [cvxgrp/cvxpy#88]
After days of work, I found the path of least resistance to getting cvxpy on Windows:

1) Install Python(x,y) - This will take care of just about ALL the standard dependencies, painlessly. I personally uninstalled my python 2.7 releases that existed beforehand,  removed the directory (by renaming it) to get rid of any libs, removed any other python versions from the PATH environment variable, and then installed Python(x,y).

2) Install ECOS (requires the steps I outlined in https://github.com/ifa-ethz/ecos/issues/53)

3) Install cvxpy.

**Comment by JoelDan192** [comment]
I suggest the instructions for Windows 64bit be updated. I passed a few hours trying to get it right. Python(X,Y) broke my python dependencies. If you have Anaconda (which large part of the community does). Someone already build the dependencies for cvxopt which is the hairy part.

It is as simple as :
- conda install -c https://conda.anaconda.org/omnia cvxopt  
- pip install cvxpy

**Comment by SteveDiamond** [comment]
Did you manage to install scs? I'm testing out your suggestion but having problems with scs.

**Comment by JoelDan192** [comment]
Yes, I just installed scs and it works:
- conda install -c https://conda.anaconda.org/omnia scs
It is version 1.1.7 though.

Note:
I tried to build scs from source. You  end up hunting down compiler versions that this package
depends on. For example, I would get an error like this:
http://stackoverflow.com/questions/28004464/error-trying-to-install-numpy

Whenever I want to install a new package that is not in the main anaconda repository. I just check in the browser of : https://anaconda.org/ . In my experience it works better that pip because these builts are specific for each system.
