### ISSUE TITLE
specifying stopping tolerance 

### ISSUE THREAD

**Issue by jask1** [cvxgrp/cvxpy#880]
cvx allows for specifying a stopping criteria (e.g., `cvx_precision  low`) and I would like to do the same in cvxpy. Is it possible to do something like this in cvxpy? The following are the links for cvx precision:

https://github.com/cvxr/CVX/blob/master/commands/cvx_precision.m
http://cvxr.com/cvx/doc/solver.html#interpreting

**Comment by akshayka** [comment]
Hey @jask1 , you can specify the tolerance by passing an additional argument to the `solve()` method. The name of the keyword argument depends on the solver you're using.

Take a look at the documentation here (and search for "eps" or "tol"): https://www.cvxpy.org/tutorial/advanced/index.html

For example, if you're using SCS and you want to increase the tolerance to 1e-8, you'd write:

```
problem.solve(solver=cp.SCS, eps=1e-8)
```

**Comment by jask1** [comment]
Thank you for your reply. I am using mosek and did use `mosek.params` to set some parameters for tolerances here:
https://docs.mosek.com/9.1/pythonapi/solving-conic.html#adjusting-optimality-criteria

However, I was looking for an equivalent of `cvx_precision low` that adjusts the three tolerances--ϵ_solver,ϵ_standard,ϵ_reduced--that are defined in terms of Matlab's machine precision tolerance: ϵ. However, I am not sure how these tolerances translate in terms of mosek's (4)-different tolerances: ε_p, ε_d, ε_g and ε_i? Thus, I was looking at the documentation of `cvx_precision` here: https://github.com/cvxr/CVX/blob/master/commands/cvx_precision.m
but, didn't really see the connection. Any assistance towards this would be much appreciated.

**Comment by akshayka** [comment]
epsilon solver corresponds to the tolerances for specific solvers. CVXPY doesn't have analogues for epsilon standard and epsilon reduced, though it might be useful for us to add them in the future.

**Comment by jask1** [comment]
Thank you - so, when one selects `cvx_precision low`, then, is this translated into a combination for mosek's (4)-tolerances: ε_p, ε_d, ε_g and ε_i? Or, epsilon solver is something entirely different? Is there a way for me to specify this? I am happy with my soln. being returned with a 1e-4 tolerance, i.e., in `cvx_slvtol` mentioned here: http://cvxr.com/cvx/doc/solver.html

**Comment by rileyjmurray** [comment]
Following up on what Akshay said, CVXPY "inaccurate" solver statuses are determined by the solver itself, in different ways.

* For MOSEK there will never actually be an "inaccurate" status code, because MOSEK removed such return codes from the version 9 release. All of the parameters you mentioned ``eps_p, eps_d, eps_g, eps_i`` are conceptually related to ``eps_solver`` (in user-facing CVX) or ``PBEST`` (deeper in the CVX code). If MOSEK fails to converge to such precision, then the tolerances are multiplied by a parameter called ``CO_TOL_NEAR_REL`` (always > 1, defaults to ``1e-4`` if I remember correctly) and checked again. If the tolerances are satisfied at that point, MOSEK returns an "optimal" status code. When using MOSEK, the CVXPY equivalent to increasing ``eps_reduced`` or ``PLOW`` is to increase ``CO_TOL_NEAR_REL``.
* For ECOS, there are parameters like ``feastol_inacc``, ``abstol_innac``, and ``reltol_inacc``. These are the rough equivalents to ``eps_reduced`` (from user-facing CVX) or ``PLOW`` (from deeper in the CVX code).
* Some solvers might not have any option to set something like ``eps_reduced`` or ``PLOW``. (Although I don't know of any off the top of my head.)

There is no way to access something like ``eps_standard`` from user-facing CVX, because CVXPY does not perform post-solver feasibility checks. This might change if progress is made on #434 .
