### ISSUE TITLE
Simple gp problem returns wrong answer.

### ISSUE THREAD

**Issue by bnaras** [cvxgrp/cvxpy#881]
**Describe the bug**
Simple minimization problem where variables are positive returns `unbounded` status

**To Reproduce**
```
import cvxpy as cp
x = cp.Variable(pos = True)
y = cp.Variable(pos = True)
prob = cp.Problem(cp.Minimize(x*y), [x <= 5, y >= 5])
prob.solve(verbose = True, gp = True) # returns unbounded
```
**Expected behavior**
Since x is declared positive, I would expect zero as the answer. 

**Output**
```
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : LO (linear optimization problem)
  Constraints            : 2               
  Cones                  : 0               
  Scalar variables       : 2               
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer started.
Optimizer terminated. Time: 0.00    


MOSEK DUAL INFEASIBILITY REPORT.

Problem status: The problem is dual infeasible

The following constraints are involved in the infeasibility.

Index    Name             Activity         Objective        Lower bound      Upper bound     
0                         -1.000000e+00                     NONE             1.609438e+00    

The following variables are involved in the infeasibility.

Index    Name             Activity         Objective        Lower bound      Upper bound     
0                         -1.000000e+00    1.000000e+00     NONE             NONE            

Interior-point solution summary
  Problem status  : DUAL_INFEASIBLE
  Solution status : DUAL_INFEASIBLE_CER
  Primal.  obj: -1.0000000000e+00   nrm: 1e+00    Viol.  con: 0e+00    var: 0e+00  

Basic solution summary
  Problem status  : DUAL_INFEASIBLE
  Solution status : DUAL_INFEASIBLE_CER
  Primal.  obj: -1.0000000000e+00   nrm: 1e+00    Viol.  con: 0e+00    var: 0e+00  
Out[2]: 0.0
```
**Version**
 - OS:  MacOS 10.15.1
 - CVXPY Version: 1.0.25

**Additional context**
None.

**Comment by rileyjmurray** [comment]
Thanks for the minimal example. I can’t debug right now but something stands out to me: MOSEK says it’s a linear problem, and that shouldn’t be the case. We recently had some issues with getting “exponential cone” problems passed correctly to mosek, and this should be one such problem.

Can you attempt with ECOS? That would help isolate if this is a bug in the mosek solver interface, or a bug earlier in problem compilation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshayka** [comment]
The output is not wrong. The problem is in fact unbounded, because 0 is not in the feasible set — GPs/LLCPs require variables to be positive, not nonnegative. A variable cannot be zero at a solution.

**Comment by akshayka** [comment]
We could however probably improve the documentation to mention this, as it’s understandably confusing.

**Comment by bnaras** [comment]
1. Ecos returns the same answerI
2. Re: Akshay's note. Since I have declared x positive, I'd have thought an answer close to macheps (effectively zero) would be returned. A slight variant that adds a constraint say x >= 1e-10 returns the correct answer

**Comment by akshayka** [comment]
@rileyjmurray , the canonicalized problem is in fact linear, there’s nothing wrong with MOSEK here. (Monomials are log-log affine.)

**Comment by rileyjmurray** [comment]
@akshayka yes I now see why this happened. Trouble is, users (myself included) interpret "unbounded" to mean "the objective is not finite". The user-specified objective is in-fact bounded below.

From the user's perspective, the issue isn't about boundedness or not, it's about attainment of the optimal solution. Since CVXPY is a numerical solver, people get used to the idea that attainment of an optimal solution is never done exactly anyway. For example, this is what happens if someone formulated the same problem doing the log-log transformation manually:
```
import cvxpy as cp
z = cp.Variable(shape=(2,))
constraints = [cp.exp(z[0]) <= 5, cp.exp(-z[1]) <= 0.2]
objective = cp.Minimize(cp.exp(z[0] + z[1]))
prob = cp.Problem(objective, constraints)
prob.solve(solver='ECOS')  # 1.4437401927291201e-08
x = cp.exp(z).value
```

**Comment by akshayka** [comment]
What you’ve done is a log transformation, not a log-log transformation. Once you take the log of the objective and both sides of the constraints, you get an LP which is in fact unbounded.

LLCPs are weird because the domain is not closed. The choice of unbounded for this scenario was a deliberate choice. Mathematically, unbounded makes sense — you can make the objective arbitrarily small and positive, hence it’s unbounded.

**Comment by bnaras** [comment]
Ok, that makes sense, now that I understand what 'unbounded' means. Yes, some documentation would help. Thanks.

**Comment by rileyjmurray** [comment]
@akshayka with that in mind, it might be useful to have cvxpy print a message when ``verbose=True`` and solving a log-log convex program. Key issues are that under the log-log transformation, the objective value the solver reports at each iteration is not necessarily easily-parsable by the user (for convex programs, the most a user has to do is flip a sign, or add a constant). Also, user-specified solver tolerances will be interpreted in log-domain. If users aren't aware of this, then they might be very confused by the solver output.

I'll also note that since solver tolerances are applied in log-domain, it could be hard for a user to specify a solver tolerance that get's them desired feasibility for the model they specified in cvxpy syntax. This connects to #434.
