### ISSUE TITLE
`is_log_log_convex` not preserved under Python built-in sum

### ISSUE THREAD

**Issue by artemyk** [cvxgrp/cvxpy#883]
The sum of two log-log convex variables should be log log convex. However, this does not work as expected with the `sum` operator. MWE:

```python
import cvxpy as cp
q = cp.Variable(2, pos=True)
print(sum(q).is_log_log_convex())       # prints False
print((q[0]+q[1]).is_log_log_convex())  # prints True
```

**Version**
 - OS: OS X, Python 3.6
 - CVXPY Version: 1.0.25

**Comment by akshayka** [comment]
@artemyk , thanks for reporting.

The reason this happens is because Python's built-in sum is implemented by accumulating the addends to 0, resulting in the expression `0 + q[0] + q[1]`, which is not log-log convex because 0 is not positive.

It might make sense for us to implement an explicit workaround for this edge case. In the meantime, you can use CVXPY's sum atom:

```
print(cp.sum(q).is_log_log_convex())  # prints True
```

**Comment by artemyk** [comment]
@akshayka I see, that makes sense.
Perhaps the overloaded __add__ method in `expression.py` could simply return `self` when adding to a 0?  I think it would resolve this issue.

**Comment by akshayka** [comment]
That's a good suggestion! Implemented in #887

**Comment by rileyjmurray** [comment]
@akshayka is there a reason you're leaving this open?

**Comment by akshayka** [comment]
Thanks for following up! I was a bit torn on whether I liked the fix. I've asked Steven to review the PR, which has not yet been merged.
