### ISSUE TITLE
scalar multiplication expands to matrix

### ISSUE THREAD

**Issue by georgh** [cvxgrp/cvxpy#885]
Hello

This is probably not a real bug, I just wanted to ask why multiplication using * is behaving like it does. Given this very small example:

```
X = cp.Variable(2)
constrains = [X <= 2.]
objective = cp.Maximize(cp.sum( X * np.array([1,1]) + np.array([1.,1.]) ) )
prob = cp.Problem(objective, constrains)
result = prob.solve()
print(result)
```

The result is 10 and not 6 as expected. Even though
`np.sum(X.value * np.array([1,1]) + np.array([1.,1.]))
`
is 6.

If the objective is changed to 
`objective = cp.Maximize(cp.sum( cp.multiply(X,np.array([1,1])) + np.array([1.,1.]) ) )`
the result is 6.

So why does .multiply behave differently to * ?

**Comment by akshayka** [comment]
The * operator is used for matrix multiplication (and multiplication of a matrix/vector by a scalar); we considered changing this with the release of 1.0, but thought it was too big of a change for our users. In retrospect, perhaps we should have made the change.

You can use the @ symbol for matrix multiplication and, as you’ve found out, the multiply atom for elementwise multiplication.

**Comment by rileyjmurray** [comment]
@akshayka I think it was reasonable (at the time) to have ``*`` overload to matrix multiplication. A core aspect of cvxpy is the ability to state a model in abstract algebraic syntax, and the matmul operator ``@`` wasn't introduced until Python 3.5. Until the matmul operator was introduced, users needed an operator for matrix multiplication, and ``*`` appealed to a wide range of users coming from matlab.

That said-- I really like the idea of cvxpy Expressions having identical semantics of numpy ndarrays, particularly in the sense of multidimensional support, broadcasting, and meanings of ``@`` and ``*``. Once cvxpy drops support for python 3.4, we could conceivably implement these changes. However, since it would be a significant breaking change, this would probably need to be a "cvxpy 2.0" kind of thing. A starting point could be to mark ``*``-based matmul calls as being deprecated. (Use of ``*`` for matrix-scalar and vector-scalar products shouldn't raise such a deprecation warning.)

**Comment by akshayka** [comment]
> A starting point could be to mark *-based matmul calls as being deprecated. (Use of * for matrix-scalar and vector-scalar products shouldn't raise such a deprecation warning.)

That's a good idea. We should do this.

**Comment by georgh** [comment]
Thank you for your explaination.
