### ISSUE TITLE
issue with pip install, manual install

### ISSUE THREAD

**Issue by mkestrada2** [cvxgrp/cvxpy#899]
**Describe the bug**
We are unable to install cvxpy or cvxopt on our system. It is a Jetson Nano (ARM based) computer running ubuntu 18.04. We have tried to use the pip install method described on the installation instructions page as well as the manual installation instructions that involve cloning the repository and using setup.py install.

Thank you for your help and i am happy to provide more info  about our system and use case it will be helpful in solving this problem!

**To Reproduce**
first error: pip install cvxpy
second error: python setup.py install

**Expected behavior**
A clean install of the latest version of cvxpy with the associated solvers

**Output**
error message presented by first error:

ERROR: Command errored out with exit status 1: /home/irg/env/bin/python3 /home/irg/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpg6qpidq0 Check the logs for full command output.

error message presented by second error, after several minutes of compiling:

scipy/fft/_pocketfft/pypocketfft.cxx:15:10: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: Command "aarch64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPOCKETFFT_PTHREADS -I/home/irg/env/include/site/python3.6 -I/home/irg/env/include/site/python3.6 -I/home/irg/env/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/irg/env/include/python3.6m -c scipy/fft/_pocketfft/pypocketfft.cxx -o build/temp.linux-aarch64-3.6/scipy/fft/_pocketfft/pypocketfft.o -MMD -MF build/temp.linux-aarch64-3.6/scipy/fft/_pocketfft/pypocketfft.o.d -std=c++14 -fvisibility=hidden" failed with exit status 1

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version:1.1.0a1

**Additional context**
We are attempting to install cvxpy and cvxopt on a Jetson Nano ARM based system.

**Comment by akshayka** [comment]
That looks like an error when compiling scipy or numpy, or some other package. CVXPY does not depend on pybind11.

In a fresh environment (without solvers and without cvxpy), can you try installing numpy and scipy via pip?

**Comment by akshayka** [comment]
To follow up:

pip is attempting to install scipy from source. This is because pypi does not have a compiled distribution of scipy for ARM-based architectures (manylinux doesn't cover ARM). For some reason, the compilation of scipy from source fails.

Unfortunately, CVXPY requires scipy, and there's no way around that requirement. To resolve your problem, you'll need install it from source.

I'm closing this issue because there's nothing we (the CVXPY team) can do to help. I'd recommend reading up on how to install scipy from source. If you're unable to figure it out, you might consider opening an issue in the scipy repository.
