### ISSUE TITLE
CVXPY + GPU error

### ISSUE THREAD

**Issue by Mahsalo** [cvxgrp/cvxpy#902]
Hi

I'm trying to run a simple optimization problem using CVXPY on GPU (on the cluster) but it gives the following error:

**import _scs_gpu
ModuleNotFoundError: No module named '_scs_gpu'** 

Is there a specific module to import to get rid of this error? I could not find an example of running optimization on GPU using CVXPY online. This is the part of the code in which I have enabled the use of GPU.

**X=prob.solve(solver=cp.SCS, gpu= True,use_indirect=True,eps=10**(-8),verbose=False)**

Any help would be appreciated.

Thanks

**Comment by rileyjmurray** [comment]
Cvxpy itself doesn’t use GPUs. The decision to use a GPU or not depends on the solver. I think SCS is the only cvxpy solver which has possible GPU support. To use that GPU support, you have to compile SCS from source (with an appropriate compiler flag).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mahsalo** [comment]
> Cvxpy itself doesn’t use GPUs. The decision to use a GPU or not depends on the solver. I think SCS is the only cvxpy solver which has possible GPU support. To use that GPU support, you have to compile SCS from source (with an appropriate compiler flag).
> 
> Sent with [GitHawk](http://githawk.com)

Thanks for your response. I have already installed scs (pip install scs) if that's what you mean. I have also tried running the following (according to one of the users):

**python3 setup.py install --scs --gpu --int**

but it does not recognize  --scs option. I don't know how to compile SCS from the source. Any hints?

**Comment by rileyjmurray** [comment]
Back when I used SCS, “pip install scs” did not include GPU support. I had to download SCS source code (from its GitHub repository) and follow GPU-specific setup instructions.

@bodono is seems that this is really an SCS question, rather than a cvxpy question. Do you agree? If so, can you take over this discussion, possibly on the SCS repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bodono** [comment]
> Thanks for your response. I have already installed scs (pip install scs) if that's what you mean. I have also tried running the following (according to one of the users):
> 
> **python3 setup.py install --scs --gpu --int**
> 
> but it does not recognize --scs option. I don't know how to compile SCS from the source. Any hints?

I just tested that and it works for me. First of all, uninstall scs (`pip uninstall scs`, you might have to run it a couple of times) and delete any artifacts in the scs directory (`rm -rf build scs.egg-info dist`). Then two things:

1) When you run that command, right at the top you should see something like:
```
=> python3 setup.py install --scs --gpu --int
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, int32=True, scs=True)
```
note the gpu=True flag, do you see that?

2) When you open a python instance try:
```
import _scs_gpu
```
what happens?

**Comment by theocnrds** [comment]
Hi,
I worked myself through this conversation because I had the same problem. The installation finally worked with cloning the git repo and installing it this way afterwards:
> => python3 setup.py install --scs --gpu --int

Now I want to use it also with cvxpy but a ModuleNotFoundError is raised with python not finding the module '_scs_gpu'. 
That part also throws a ModuleNotFoundError:
> 1. When you open a python instance try:
> 
> ```
> import _scs_gpu
> ```
> 
> what happens?

Do you have another advice how to process this problem?

Thanks

**Comment by bodono** [comment]
Can you clean out the repo then paste in here what you see when you try to install?

**Comment by theocnrds** [comment]
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, int32=False, scs=True)
running install
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/usr/local/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/usr/local/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include']}
scs 2.1.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/scs-2.1.2-py3.6-linux-x86_64.egg
Processing dependencies for scs==2.1.2
Searching for scipy==1.3.3
Best match: scipy 1.3.3
Adding scipy 1.3.3 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for numpy==1.17.4
Best match: numpy 1.17.4
Adding numpy 1.17.4 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.6 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for scs==2.1.2

**Comment by bodono** [comment]
This line:
`scs 2.1.2 is already the active version in easy-install.pth`
indicates to me that you already have SCS installed. Did you uninstall it first? When I run it on a fresh instance I see
`Adding scs 2.1.2 to easy-install.pth file`

**Comment by theocnrds** [comment]
Yes I uninstalled it before, but only once. Additionally I removed the folder manually and now I get the following:

> Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, int32=False, scs=True)
running install
running bdist_egg
running egg_info
creating scs.egg-info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
writing manifest file 'scs.egg-info/SOURCES.txt'
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/usr/local/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/usr/local/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include']}
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/scsmodule.c:5:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
scs/src/rw.c: In function ‘scs_read_data’:
scs/src/rw.c:143:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&(file_int_sz), sizeof(uint32_t), 1, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
MANY TIMES
...
scs/src/rw.c:96:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(A->i, sizeof(scs_int), Anz, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/scsmodule.c:5:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
scs/src/rw.c: In function ‘scs_read_data’:
scs/src/rw.c:143:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&(file_int_sz), sizeof(uint32_t), 1, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
MANY TIMES
...
scs/src/rw.c:96:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(A->i, sizeof(scs_int), Anz, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/scsmodule.c:5:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
scs/src/rw.c: In function ‘scs_read_data’:
scs/src/rw.c:143:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&(file_int_sz), sizeof(uint32_t), 1, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
MANY TIMES
...
scs/src/rw.c:96:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(A->i, sizeof(scs_int), Anz, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from python_linsys/private.c:2:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/scsmodule.c:5:
/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
scs/src/rw.c: In function ‘scs_read_data’:
scs/src/rw.c:143:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&(file_int_sz), sizeof(uint32_t), 1, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
MANY TIMES
...
scs/src/rw.c:96:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(A->i, sizeof(scs_int), Anz, fin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>Adding scs 2.1.2 to easy-install.pth file

>Installed /usr/local/lib/python3.6/dist-packages/scs-2.1.2-py3.6-linux-x86_64.egg
Processing dependencies for scs==2.1.2
Searching for scipy==1.3.3
Best match: scipy 1.3.3
Adding scipy 1.3.3 to easy-install.pth file

>Using /usr/local/lib/python3.6/dist-packages
Searching for numpy==1.17.4
Best match: numpy 1.17.4
Adding numpy 1.17.4 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.6 script to /usr/local/bin

>Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for scs==2.1.2

But I still get the ModuleNotFoundError when importing _scs_gpu

**Comment by bodono** [comment]
Ok now what do you get when you `ls /usr/local/lib/python3.6/dist-packages/scs-2.1.2-py3.6-linux-x86_64.egg`

**Comment by theocnrds** [comment]
EGG-INFO
__pycache__
scs
_scs_direct.cpython-36m-x86_64-linux-gnu.so
_scs_direct.py
_scs_gpu.cpython-36m-x86_64-linux-gnu.so
_scs_gpu.py
_scs_indirect.cpython-36m-x86_64-linux-gnu.so
_scs_indirect.py
_scs_python.cpython-36m-x86_64-linux-gnu.so
_scs_python.py

**Comment by bodono** [comment]
So it's installed, probably something is wrong with the way your python install is using the paths. You could try adding that directory to the `PYTHONPATH`.

**Comment by theocnrds** [comment]
Okay, after a short search on google I did it that way:

`import sys`
`sys.path.append('/usr/local/lib/python3.6/dist-packages/')`

That doesn't change anything. I have to admit that I'm not a pro programmer yet. :'D
Also I'm working on Google Colab, which is a little frustrating.

**Comment by SteveDiamond** [comment]
You guys can keep talking, but this is not a cvxpy issue.

**Comment by vilsaira** [comment]
This is still not a cvxpy issue but as I failed to find conversation/solutions elsewhere in the web despite this being a bit old question, here is my solution to it. Worked in Google Colab and might work in other venvs too with adjustments.

In **Colab**
`!pip install cvxpy`
`!pip uninstall scs -y`
`!git clone --recursive https://github.com/bodono/scs-python.git`
`!cd /content/scs-python && python -m pip install . --install-option="--scs --gpu --int"`

Second row uninstalls scs that comes with cvxpy. Third row clones the scs-python to your Colab env and fourth row cds to the cloned directory and runs install. This approach sets PYTHONPATH correctly withing venv thus avoiding the problem in path that comes with using `python3 setup.py install --scs --gpu --int`.

After that `import _scs_gpu` worked for me in Colab.

**Comment by YiJU-thu** [comment]
> python3 setup.py install --scs --gpu --int
Hi, I am trying to work on Colab with GPU accelaration for cvxpy. Your reply excites me, but I tried, but not succeed. Do i need anything besides the four lines of commands? After running that I would have "Successfully installed scs-3.0.0", but when I run "import _scs_gpu", it still "ModuleNotFoundError: No module named '_scs_gpu'". Thank you so much!

**Comment by YiJU-thu** [comment]
> This is still not a cvxpy issue but as I failed to find conversation/solutions elsewhere in the web despite this being a bit old question, here is my solution to it. Worked in Google Colab and might work in other venvs too with adjustments.
> 
> In **Colab** `!pip install cvxpy` `!pip uninstall scs -y` `!git clone --recursive https://github.com/bodono/scs-python.git` `!cd /content/scs-python && python -m pip install . --install-option="--scs --gpu --int"`
> 
> Second row uninstalls scs that comes with cvxpy. Third row clones the scs-python to your Colab env and fourth row cds to the cloned directory and runs install. This approach sets PYTHONPATH correctly withing venv thus avoiding the problem in path that comes with using `python3 setup.py install --scs --gpu --int`.
> 
> After that `import _scs_gpu` worked for me in Colab.

Hi, I am trying to work on Colab with GPU accelaration for cvxpy. Your reply excites me, but I tried, but not succeed. Do i need anything besides the four lines of commands? After running that I would have "Successfully installed scs-3.0.0", but when I run "import _scs_gpu", it still "ModuleNotFoundError: No module named '_scs_gpu'". Thank you so much!

**Comment by SherryC98** [comment]
I tried this：

pip uninstall scs -y
pip install scs

which solved my problem

**Comment by xxxinaw** [comment]
i have anonther problem. i have the same content with above repo but come up with "undefined symbol: cusparseDcsrmv"
the problem comes with the following
python3 setup.py install --scs --gpu --int
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, gpu_atrans=True, int32=True, scs=True)
running install
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/home/gyw/anaconda3/envs/GM/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include', '/home/gyw/anaconda3/envs/GM/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/home/gyw/anaconda3/envs/GM/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/usr/local/include', '/usr/include', '/home/gyw/anaconda3/envs/GM/include']}
Adding scs 2.1.2 to easy-install.pth file

Installed /home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/scs-2.1.2-py3.6-linux-x86_64.egg
Processing dependencies for scs==2.1.2
Searching for scipy==1.4.1
Best match: scipy 1.4.1
Adding scipy 1.4.1 to easy-install.pth file

Using /home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Adding numpy 1.19.5 to easy-install.pth file
Installing f2py script to /home/gyw/anaconda3/envs/GM/bin
Installing f2py3 script to /home/gyw/anaconda3/envs/GM/bin
Installing f2py3.6 script to /home/gyw/anaconda3/envs/GM/bin

Using /home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages
Finished processing dependencies for scs==2.1.2
(GM) gyw@user-Super-Server:~/code/GMTracker-main/scs-python$ python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _scs_gpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/scs-2.1.2-py3.6-linux-x86_64.egg/_scs_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsrmv
>>> exit()
 someone pls help me :(

**Comment by bodono** [comment]
What version of SCS are you using? `cusparseDcsrmv` is no longer in CuSparse and SCS moved over to the new API a while ago. I would suggest updating SCS first to see if that fixes it.

**Comment by bodono** [comment]
Oh I see you're using SCS 2.1.2, I would strongly recommend updating to SCS 3+, it's overall faster and more robust, plus fixes things like this.

**Comment by xxxinaw** [comment]
### **yes, upgrading can fix the cusparse problem. but it also brings error as follows:**

Traceback (most recent call last):
  File "gmtracker_app.py", line 285, in <module>
    args.max_age, args.n_init, args.reid_thr, args.checkpoint_dir)
  File "gmtracker_app.py", line 239, in run
    frame_callback(frame_idx)
  File "gmtracker_app.py", line 226, in frame_callback
    tracker.update(detections, seq_info["sequence_name"], frame_idx, checkpoint_dir)
  File "/home/gyw/code/GMTracker/utils/tracker.py", line 119, in update
    self._match(detections,video,frame,checkpoint_dir)
  File "/home/gyw/code/GMTracker/utils/tracker.py", line 149, in _match
    self.max_age, self.tracks, detections, confirmed_tracks,reid_thr=self.reid_thr,seq_name=video,ckp_dir=checkpoint_dir)
  File "/home/gyw/code/GMTracker/GMMOT/assignment.py", line 143, in graph_matching
    track_indices_l, unmatched_detections,reid_thr,seq_name,ckp_dir)
  File "/home/gyw/code/GMTracker/GMMOT/assignment.py", line 95, in quadratic_matching
    indices, thr_flag = graphnet.forward(data1, data2, kf_gate, reid_thr, iou, start_src, end_src, start_tgt, end_tgt, seq_name, inverse_flag=False)
  File "/home/gyw/code/GMTracker/GMMOT/gmatching.py", line 107, in forward
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 928, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 308, in solve_via_data
    results = scs.solve(args, cones, verbose=verbose, **solver_opts)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/scs-3.2.7-py3.6-linux-x86_64.egg/scs/__init__.py", line 177, in solve
    solver = SCS(data, cone, **settings)
  File "/home/gyw/anaconda3/envs/GM/lib/python3.6/site-packages/scs-3.2.7-py3.6-linux-x86_64.egg/scs/__init__.py", line 140, in __init__
    **self._settings
ValueError: Error parsing inputs

### i've been working with it for days, is it because the code is incompatible with the upgraded version or its just because the code? thank you so much for your help!

**Comment by bodono** [comment]
Something strange is going on with the data getting passed to SCS, unfortunately the errors are not descriptive (from the python side). Does you code work with the non-gpu SCS direct version (ie, the default)? If it does then it's likely an issue with the width of the integer type, otherwise something else is wrong with how the data is getting passed.
