### ISSUE TITLE
CVXPY crashes with Gurobi + QCPDual=0 + SOC

### ISSUE THREAD

**Issue by psa0000** [cvxgrp/cvxpy#933]
**Describe the bug**
CVXPY crashes with Gurobi when both "not dual" (QCPDual=0) and  "second order cones" (SOC)

**To Reproduce**
```python
import gurobipy as gp 
import numpy
import cvxpy

verbose=True
# SOC example  (I assume any SOC would do)
m = 3
n = 10
p = 5
n_i = 5
numpy.random.seed(2)
f = numpy.random.randn(n)
A = []
b = []
c = []
d = []
x0 = numpy.random.randn(n)
for i in range(m):
    A.append(numpy.random.randn(n_i, n))
    b.append(numpy.random.randn(n_i))
    c.append(numpy.random.randn(n))
    d.append(numpy.linalg.norm(A[i]@x0 + b, 2) - c[i].T@x0)
F = numpy.random.randn(p, n)
g = F@x0

# Define and solve the CVXPY problem.
x = cvxpy.Variable(n)
# We use cvxpy.SOC(t, x) to create the SOC constraint ||x||_2 <= t.
soc_constraints = [
        cvxpy.SOC(c[i].T@x + d[i], A[i]@x + b[i]) for i in range(m)
]
prob = cvxpy.Problem(cvxpy.Minimize(f.T@x),
                    soc_constraints + [F@x == g])
    
for dual in [1,0]:
    prob.solve(solver=cvxpy.GUROBI,verbose=verbose,QCPDual=dual)
    # Print result.
    print("The optimal value is", prob.value)
```
**Expected behavior**
QCPDual=1 (dual) is fine but for QCPDual=0 (prime)  the crash occurs just after verbose shows successful solution is found, but before  exiting  prob.solve.  So I guess probem solves in Gurobi but CVXPY does not cope with the lask of dual solution.

**Output**
//////////
Barrier solved model in 9 iterations and 0.02 seconds
Optimal objective -9.58269205e+00

Warning: to get QCP duals, please set parameter QCPDual to 1

Traceback (most recent call last):
  File "C:\Users\psa\Dropbox\GitPython\cxvpy1\cxvpyBug_Guribi_SOC1.py", line 69, in <module>
    prob.solve(solver=cvxpy.GUROBI,verbose=verbose,QCPDual=dual)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 574, in _solve
    self.unpack_results(solution, full_chain, inverse_data)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 713, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "C:\IntelPython3\lib\site-packages\cvxpy\reductions\chain.py", line 73, in invert
    solution = r.invert(solution, inv)
  File "C:\IntelPython3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\gurobi_conif.py", line 106, in invert
    solution['eq_dual'],
KeyError: 'eq_dual'
Press any key to continue . . .

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.0.25 
Python 3.6.9 :: Intel Corporation

**Additional context**
As a work around, can  I at least set a variable in CVXPY to say there will be no dual solution
?

**Comment by SteveDiamond** [comment]
Try installing cvxpy version 1.1.

**Comment by akshayka** [comment]
To add on to Steven's recommendation, 1.1 is still in alpha. You can install it with

```
pip install --pre cvxpy
```

**Comment by psa0000** [comment]
Thanks to all

pip install --pre cvxpy              

still go goes  for  cvxpy1.0.25
 
```
C:.>pip install --pre cvxpy
Requirement already satisfied: cvxpy in c:\intelpython3\lib\site-packages (1.0.25)
Requirement already satisfied: osqp>=0.4.1 in c:\intelpython3\lib\site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: numpy>=1.15 in c:\intelpython3\lib\site-packages (from cvxpy) (1.16.4)
Requirement already satisfied: six in c:\intelpython3\lib\site-packages (from cvxpy) (1.12.0)
Requirement already satisfied: scs>=1.1.3 in c:\intelpython3\lib\site-packages (from cvxpy) (2.1.1.post2)
Requirement already satisfied: multiprocess in c:\intelpython3\lib\site-packages (from cvxpy) (0.70.9)
Requirement already satisfied: ecos>=2 in c:\intelpython3\lib\site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: scipy>=1.1.0 in c:\intelpython3\lib\site-packages (from cvxpy) (1.3.0)
Requirement already satisfied: future in c:\intelpython3\lib\site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Requirement already satisfied: dill>=0.3.1 in c:\intelpython3\lib\site-packages (from multiprocess->cvxpy) (0.3.1.1)
```

**Comment by akshayka** [comment]
Sorry, add the upgrade flag:

```
pip install --pre --upgrade cvxpy
```

**Comment by psa0000** [comment]
I uninstalled and reinstalled and got cvxpy-1.1.0a2  ok. 
```
C:\Users\psa>pip install --pre cvxpy
Collecting cvxpy
  Downloading cvxpy-1.1.0a2-cp36-cp36m-win_amd64.whl (743 kB)
     |████████████████████████████████| 743 kB 1.1 MB/s
Requirement already satisfied: scs>=1.1.3 in c:\intelpython3\lib\site-packages (from cvxpy) (2.1.1.post2)
Requirement already satisfied: osqp>=0.4.1 in c:\intelpython3\lib\site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: numpy>=1.15 in c:\intelpython3\lib\site-packages (from cvxpy) (1.16.4)
Requirement already satisfied: ecos>=2 in c:\intelpython3\lib\site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: scipy>=1.1.0 in c:\intelpython3\lib\site-packages (from cvxpy) (1.3.0)
Requirement already satisfied: future in c:\intelpython3\lib\site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Installing collected packages: cvxpy
Successfully installed cvxpy-1.1.0a2

C:\Users\psa>pip install scipi
```

but my test  now fails related to scipi.
```
cvxpy= 1.1.0a2
 
Traceback (most recent call last):
  File "C:\Users\psa\Dropbox\GitPython\cxvpy1\cxvpyBug_Guribi_SOC1.py", line 72, in <module>
    prob.solve(solver=cvxpy.GUROBI,verbose=verbose,QCPDual=dual)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 310, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 626, in _solve
    self, data, warm_start, verbose, kwargs)
  File "C:\IntelPython3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 315, in solve_via_data
    solver_opts, problem._solver_cache)
  File "C:\IntelPython3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\gurobi_conif.py", line 175, in solve_via_data
    A, b)
  File "C:\IntelPython3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\gurobi_conif.py", line 268, in add_model_lin_constr
    for (i, j), c in mat.iteritems():
  File "C:\IntelPython3\lib\site-packages\scipy\sparse\base.py", line 688, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: iteritems not found
Press any key to continue . . .
```

**Comment by rileyjmurray** [comment]
@psa0000 you can ignore that error. It was resolved in #912 on Jan 12. The most recent alpha release of cvxpy (1.1.0a2; the one you have) was released on Jan 6, so that's why you're seeing the error.

If you have an immediate need for the Gurobi conic interface, I'm afraid I'll have to recommend installing cvxpy from source (this repo's master branch).

Minor remark: Gurobi has two interface files in cvxpy: a conic interface, and a QP interface. Both the conic and QP interfaces handle mixed-integer linear programs, and quadratic objective functions. The conic interface just also allows for second order cone constraints (what some might call a "QCQP").  There has been some discussion about whether we really need both interface files. See @rostyboost 's comment https://github.com/cvxgrp/cvxpy/issues/913#issuecomment-569943131.

Since I think we've really pinned down the issue here, I'm going to close this ticket. If you have additional questions you can still comment on this thread; just tag me in the comment if you make one.

**Comment by psa0000** [comment]
Compiling  cvxpy in Windows looks too tedious so, I will wait. Any
ideas how long?

Peter

**Comment by rileyjmurray** [comment]
I'm not sure when the next alpha release will be. The only updates since 1.1.0a2 were this Gurobi fix, and introducing a deprecation warning. However introducing the deprecation warning also involved dropping python 2.7 and 3.4, so the overall change was significant. I'll talk to Steven and Akshay about a timeline.

But to reiterate: if you're in academia I'd recommend temporarily using another solver. The CPLEX interface supports SOC constraints, and although it has an issue with dual variables at the moment (#920 ) the primal solutions are fine. The MOSEK interface is currently the most general-purpose supported by CVXPY. If you aren't in academia and can do without mixed integer support, I'd recommend ECOS for the time being.

**Comment by SteveDiamond** [comment]
We can do another alpha release soon, sometime this week at least. The big delay is moving the alpha into stable.

**Comment by SteveDiamond** [comment]
I've pushed a new alpha release to pypi. @psa0000 if you install with pip again (upgrading obviously) it should work.

**Comment by psa0000** [comment]
Thanks for  Steve for cvxpy1.1.0a3.   Gurobi now works,  but Mosek and ECOS now fail  e.g.
```
    prob.solve(solver=cvxpy.MOSEK,verbose=verbose,mosek_params=mosekpar)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 325, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 642, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 882, in unpack_results
    self.unpack(solution)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 840, in unpack
    c.save_dual_value(solution.dual_vars[c.id])
  File "C:\IntelPython3\lib\site-packages\cvxpy\constraints\second_order.py", line 121, in save_dual_value
    cone_size = 1 + self.args[1].shape[self.axis]
IndexError: tuple index out of range
```
I could not test SCS as it was not included

**Comment by rileyjmurray** [comment]
SCS is a required solver. You shouldn’t be able to install CVXPY without it. Something strange is happening here.

Separately, these errors with ECOS and MOSEK, are they in CVXPY unittests, or are they in a model you made?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rileyjmurray** [comment]
I just checked our automated testing, and the latest commit passes. ECOS is a required solver, so if you’re seeing an error I’m guessing it’s with a model you created. We know that some dual variable recovery situations aren’t covered by unittests, so perhaps the error you’re seeing falls into one of those untested cases.

If indeed you’re using a model of your own, please post a minimal version of it on a separate GitHub issue.

@SteveDiamond the TravisCI build failed to deploy some instances. The failure looks like it was due to network errors. Can you trigger a new Travis build for the master branch? (You should be able to do this directly on the Travis website once you log in.)
 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SteveDiamond** [comment]
@rileyjmurray I've retriggered the builds. I restarted them once before already, and they failed again. Kind of strange.

**Comment by rileyjmurray** [comment]
I looked at them in more detail. There are a couple minor issues, at least one of which stemmed from my recent PR.

The issue stemming from the PR wasn't apparent, because the relevant code snippet is only run when we attempt to deploy with Anaconda.

The other issue is related to the version of ``readme_renderer``. I'm pretty sure this issue can be fixed with a change of conda channel (from default, to conda-forge).

**Comment by SteveDiamond** [comment]
Ok great! Do you want to fix it? Feel free to just push a patch to master.

**Comment by rileyjmurray** [comment]
Yeah I'll fix it. I'll probably get to it tomorrow though. I want to make sure that my fixes take care of the entire issue in one PR, and there will be a little tinkering to make sure this happens.

**Comment by psa0000** [comment]
cvxpu1.1.0a3:
Mosek, Gurobi, and ECOS work on simple cvxpy  SOC example for both dual and prime (where applicable)

I am trying (struggling)  to make a simple enough example to demonstrate the "new" failure with Mosek/ECOS...

 Does the error above, coming just after the Gurobi fix and  being the same for MOSEK and ECOS give you  clue? Here from ECOS
```
OPTIMAL (within feastol=2.6e-10, reltol=9.3e-09, abstol=3.1e-03).
Runtime: 0.173714 seconds.

Traceback (most recent call last):
 ///////////////////////
    prob.solve(solver=cvxpy.ECOS,verbose=verbose)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 325, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 642, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 882, in unpack_results
    self.unpack(solution)
  File "C:\IntelPython3\lib\site-packages\cvxpy\problems\problem.py", line 840, in unpack
    c.save_dual_value(solution.dual_vars[c.id])
  File "C:\IntelPython3\lib\site-packages\cvxpy\constraints\second_order.py", line 121, in save_dual_value
    cone_size = 1 + self.args[1].shape[self.axis]
IndexError: tuple index out of range 
```

**Comment by rileyjmurray** [comment]
The clue is that SOC constraints are being specified in a different way compared to your example at the top of this thread. The shapes of the arguments, or the ``axis`` option are almost certainly different. I'm going to create another GitHub issue for this. We would really appreciate it if you could provide specific code where this happens. As long as the code is confined to a single Python file (you can like to such a file by pastebin, or something similar) then we can investigate.
