### ISSUE TITLE
ECOS_BB returns "optimal" status, but very infeasible solution

### ISSUE THREAD

**Issue by vutuong** [cvxgrp/cvxpy#946]
**Describe the bug**
CVXPY return wrong result

**To Reproduce**
I have this script file. After ran this code, i got the wrong result that is not optimal and also violates constraint ( constraint_3)
````
import json
# import matplotlib.pyplot as plt
from random import *
import cvxpy as cp
import numpy as np
import pandas as pd
number_of_edge = 10
beta = 1
d = np.random.randn(number_of_edge, number_of_edge)
u = np.random.randn(number_of_edge)

migration_threat = 1000
latency_threat = 2000

F = cp.Variable(pos=True, name="F")
G = cp.Variable(pos=True, name="G")
y = cp.Variable(shape=(number_of_edge, number_of_edge), boolean=True)
objective = cp.Maximize(cp.log(migration_threat - F) + cp.log(latency_threat - G))
constraints = []

# Constraint: each base station connect to only one edge_server
for j in range(number_of_edge):
    constraint_2 = 0
    for i in range(number_of_edge):
        constraint_2 = constraint_2 + y[i,j]
    constraints += [constraint_2 - 1 == 0]

# Constraint: at least one edge have service
constraint_3 = 0
for i in range(number_of_edge):
    for j in range(number_of_edge):
        constraint_3 = constraint_3 + y[i,j]
constraints += [constraint_3 >= number_of_edge]
# Constraint: one edge serve for max n base_station
for i in range(number_of_edge):
    constraint_4 = 0
    for j in range(number_of_edge):
        constraint_4 = constraint_4 + y[i,j]
    constraints += [constraint_4 <= 4]
# Constraint: migration cost lower than optimal value
constraint_5 = sum(sum(y[i,j]*d[i,0]*beta for i in range(number_of_edge)) for j in range(number_of_edge))
constraints += [F >= constraint_5]

#Constraint: latency cost lower than optimal value
constraint_6 = sum(y[i,j]*d[i,j]*u[j] for j in range(number_of_edge) for i in range(number_of_edge))
constraints += [G >= constraint_6]
constraints += [F <= migration_threat]
constraints += [G <= latency_threat]
prob = cp.Problem(objective, constraints)
print("Optimal value", prob.solve())
print("Optimal var")
print(y.value)
print(F.value)
print(G.value)
print(prob.status)
```


**Output**
```
Optimal value -0.0
Optimal var
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
0.0
optimal
```
**Version**
 - OS: Same problem with Window10 and Linux 16.04
 - CVXPY Version: 1.0.25

**Additional context**
Add any other context about the problem here.

**Comment by rileyjmurray** [comment]
The issue you're seeing here is the result of using ECOS_BB, which ships with cvxpy by default. Although ECOS is generally a reliable solver, the variant ECOS_BB is known to have issues.

In your example problem ECOS returns an "unknown" status code, but ECOS_BB doesn't process that status code properly. You can see that ECOS struggles by calling ``prob.solve(verbose=True)``. In any case, once ECOS passes control to ECOS_BB, ECOS_BB thinks it solved the problem, and it returns a solution together with the "optimal" status code. If you try this problem with MOSEK, you'll get the output
```
Optimal value 14.508657100385578
Optimal var
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 1. 1. 0. 1. 0. 0. 0.]]
0.00016296604860599473
0.0003243841958919802
optimal
```
which should be correct. I should point out that MOSEK is really your only option here: no other mixed-integer commercial solver supports the exponential cone, which is needed here because of the logarithmic terms in the objective.

There are two things CVXPY can do to improve here. First, we can take action about ECOS_BB's unreliability. This has come up before in #799 #631 #578. The second thing CVXPY can do is to not take a solver's word for it that a solution is feasible. There has been some discussion about adding post-solver feasibility checks (#434) but so far nothing has come of it.

If you don't have access to MOSEK (i.e. if you are in industry, or a hobbyist), then your best bet is to employ a piecewise approximation (or rather successive piecewise approximations) of the logarithm. Piecewise approximations were the standard approach for this kind of problem for many years, and so you should be able to find an explanation for how to accomplish this.

**Comment by vutuong** [comment]
@rileyjmurray  Thank you for your reply. It work for my problem.
