### ISSUE TITLE
Add constraint that include multiplication between element y[i,j] and sum of row in matrix y

### ISSUE THREAD

**Issue by vutuong** [cvxgrp/cvxpy#957]
**Is your feature request related to a problem? Please describe.**
`y = cp.Variable(shape=(len1, len2), boolean =True)`
I try to add a constraint that include this multiplication : `y[i,j]*sum(y[i,j] for i in range(len1))`
Unlucky, when i try to solve the problem with CVXPY, i got error: "The following constraints are not DCP" 
With Gurobi, there are no problem when i add this kind of constraint.

**Describe the solution you'd like**
Is there any way to add this kind of constraint ?

**Comment by rileyjmurray** [comment]
The code snippet ``y[i,j]*sum(y[i,j] for i in range(len1))`` doesn't quite make sense, because the index ``i`` is used both inside and outside of the sum. I assume you mean something more like ``y[k,j]*sum(y[i,j] for i in range(len1))``.

Forming an expression like ``expr = y[k,j]*sum(y[i,j] for i in range(len1))`` usually isn't allowed in cvxpy. It's rare that constraints specified like ``expr <= a`` or ``expr == a`` end up being convex (even when ``y`` is a continuous variable). Usually I'd refer someone in your situation to CVXPY's list of nonlinear operators: https://www.cvxpy.org/tutorial/functions/index.html#scalar-functions, so you can try to write your problem in a convex fashion. In your situation I think CVXPY's nonlinear operators will not be enough, because your ``expr`` is bilinear. There are very, very few situations when a constraint specified on a bilinear expression ends up being convex. 

GUROBI is probably allowing your constraint, because GUROBI allows the user to specify nonconvex quadratic constraints.
