### ISSUE TITLE
Incremental Summation of Expressions in CVXPY

### ISSUE THREAD

**Issue by adishavit** [cvxgrp/cvxpy#970]
I need to incrementally build a CVXPY expression, e.g. a sum.  
At the moment I'm using:

```python
sum_expr = None

for ...
   var = cp.Variable(...)
   if sum_expr:
      sum_expr += var
   else:
      sum_expr = var

# use sum_expr 
```
Is there a cleaner, more concise way to do this?  

Is there some default NOP/Null/Void/Nil value I can use to initialize `sum_expr` so that I can avoid the `if` statement and just use the `+=`?

For sums I can use a Constant 0, but that extends the expression tree and does not generalized to other ops.

(cross posted [here](https://stackoverflow.com/questions/60743555/incremental-summation-of-expressions-in-cvxpy)).

**Comment by akshayka** [comment]
As you mention, you can use `0` for sums. For multiplication, you could use `1`. In general, there is no NULL expression.

By the way, if your for loop is very large, compiling the CVXPY problem containing `sum_expr` might take a significant amount of time (ie, the call to `problem.solve()` might take a significant amount of time, even before the solver is invoked).  If you find that the compilation time is too long, vectorizing the construction of `sum_expr` (so that the expression tree is smaller) should decrease it substantially.  Long compilation times for large expression trees is a known issue that we hope to address in the future.

**Comment by adishavit** [comment]
Then I guess a Null/Empty expression is a feature-request :-). 

What do you mean by "vectorizing the construction of sum_expr (so that the expression tree is smaller) "?

**Comment by akshayka** [comment]
Sure! Check out this guide, written by one of our developers:

https://github.com/cvxgrp/cvxpy/blob/master/examples/notebooks/building_models_with_fast_compile_times.ipynb

If you don't see any performance issues, then there's no need to worry about this. In fact, I believe that we automatically vectorize sum atoms for you.

**Comment by akshayka** [comment]
> Then I guess a Null/Empty expression is a feature-request

Thanks for the feature request! We might not implement this particular feature, as we prefer a simple explicit API. Hopefully it's not too much work to default-initialize your expressions as appropriate. In general, don't worry about extending the expression tree by just one node (a `0`, or a `1`) --- the semantics of the program will be identical, and performance should be virtually unchanged by adding just one extra node.

**Comment by adishavit** [comment]
Cool. Thanks for the prompt answers 🙂
