### ISSUE TITLE
Increase warning level when users use * for matmul

### ISSUE THREAD

**Issue by juesato** [cvxgrp/cvxpy#980]
For many users coming from numpy, it is very natural to use `*` for element-wise multiplication.

In cvxpy, when one value is a scalar, `*` has the same behavior as numpy, but when both values are vectors/matrices, cvxpy will perform a matrix multiplication instead. This behavior is now deprecated in favor of `@`, as of https://github.com/cvxgrp/cvxpy/pull/926.

I think it'd be better to make this deprecation more visible. I would consider raising an error, or if not, changing `DeprecationWarning` to `UserWarning`, since Python hides all `DeprecationWarning`s by default, unless triggered from `__main__`.

In the following example, a new user might expect `ab - a*b` to be a 0 vector. This code would then fail silently.
```
def cvx_toy_example():
  a = cp.Constant([1.0, 2.0])
  b = cp.Constant([3.0, 4.0])
  ab = cp.Constant([3.0, 8.0])
  d = (ab - a * b)[0]
  problem = cp.Problem(cp.Minimize(d), [])
  problem.solve(solver=cp.SCS)
  print(d.value)  # -8.0, not 0.0

cvx_toy_example()
```

Also, if it's possible to add the deprecation warning to release 1.0.29, that'd be great since then I could raise the warning level in my own code. Google currently uses latest release (1.0.28 right now), so I can't just use cvxpy from master at HEAD. Totally understood if not though.

**Comment by rileyjmurray** [comment]
Unfortunately, adding a warning to a 1.0.x release would require changing more than a couple lines of code. Separetely, I think this kind of deprecation is better suited to a major or minor release, rather than a patch.

In your situation I'd recommend installing the alpha release of cvxpy 1.1 (which is really more of a late beta at this point); you can do this with ``pip install --pre cvxpy``.

As to raising warning level, raising an *error* would be too fast of change-- it would help new users, but it has a significant chance of breaking code for our existing users. That said, I didn't know that DeprecationWarnings are suppressed by default. I think changing to a UserWarning is appropriate; if you want to make a PR for this I'd be happy to review. I'll leave this issue open until the warning type is changed on master.

**Comment by juesato** [comment]
Thanks for the quick response. Hope all is well.

That's totally understandable - I expected it'd be a fairly large change. Internally to Google, it'd be hard to install 1.1 just for myself (but that's just an idiosyncrasy of Google's infra, and shouldn't affect cvxpy dev). Incidentally, are there any plans on the horizon to release v1.1?

Changing to UserWarning sounds good to me; I'll make a PR for that.

**Comment by rileyjmurray** [comment]
The hope is to release 1.1 very soon. We have a GitHub issue which tracks TODOs for a 1.1 release. I believe the only major things delaying a release are related to how cvxpy handles QPs, which is narrow part of the larger codebase.
